/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_maquette_ajout_modif_supp_offre (void)
{
  GtkWidget *maquette_ajout_modif_supp_offre;
  GtkWidget *fixed1;
  GtkWidget *ajout_offre;
  GtkWidget *mod_sup_offre;
  GtkWidget *recherche_hebergement;
  GtkWidget *mod_sup_reservation;
  GtkWidget *ajout_reservation;

  maquette_ajout_modif_supp_offre = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (maquette_ajout_modif_supp_offre), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (maquette_ajout_modif_supp_offre), fixed1);

  ajout_offre = gtk_button_new_with_mnemonic (_("ajouter un offre"));
  gtk_widget_show (ajout_offre);
  gtk_fixed_put (GTK_FIXED (fixed1), ajout_offre, 368, 72);
  gtk_widget_set_size_request (ajout_offre, 176, 40);

  mod_sup_offre = gtk_button_new_with_mnemonic (_("modifier/supprimer\nun offre"));
  gtk_widget_show (mod_sup_offre);
  gtk_fixed_put (GTK_FIXED (fixed1), mod_sup_offre, 368, 136);
  gtk_widget_set_size_request (mod_sup_offre, 176, 64);

  recherche_hebergement = gtk_button_new_with_mnemonic (_("rechercher hebergement"));
  gtk_widget_show (recherche_hebergement);
  gtk_fixed_put (GTK_FIXED (fixed1), recherche_hebergement, 368, 208);
  gtk_widget_set_size_request (recherche_hebergement, 176, 40);

  mod_sup_reservation = gtk_button_new_with_mnemonic (_("modifier/supprimer\nreservation"));
  gtk_widget_show (mod_sup_reservation);
  gtk_fixed_put (GTK_FIXED (fixed1), mod_sup_reservation, 376, 328);
  gtk_widget_set_size_request (mod_sup_reservation, 160, 48);

  ajout_reservation = gtk_button_new_with_mnemonic (_("ajouter reservation"));
  gtk_widget_show (ajout_reservation);
  gtk_fixed_put (GTK_FIXED (fixed1), ajout_reservation, 368, 264);
  gtk_widget_set_size_request (ajout_reservation, 168, 40);

  g_signal_connect ((gpointer) ajout_offre, "clicked",
                    G_CALLBACK (on_ajoutoffre_clicked),
                    NULL);
  g_signal_connect ((gpointer) mod_sup_offre, "clicked",
                    G_CALLBACK (on_mod_supoffre_clicked),
                    NULL);
  g_signal_connect ((gpointer) recherche_hebergement, "clicked",
                    G_CALLBACK (on_rechercher_hebergement_clicked),
                    NULL);
  g_signal_connect ((gpointer) mod_sup_reservation, "clicked",
                    G_CALLBACK (on_mod_sup_reservation_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajout_reservation, "clicked",
                    G_CALLBACK (on_ajouter_reservation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (maquette_ajout_modif_supp_offre, maquette_ajout_modif_supp_offre, "maquette_ajout_modif_supp_offre");
  GLADE_HOOKUP_OBJECT (maquette_ajout_modif_supp_offre, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (maquette_ajout_modif_supp_offre, ajout_offre, "ajout_offre");
  GLADE_HOOKUP_OBJECT (maquette_ajout_modif_supp_offre, mod_sup_offre, "mod_sup_offre");
  GLADE_HOOKUP_OBJECT (maquette_ajout_modif_supp_offre, recherche_hebergement, "recherche_hebergement");
  GLADE_HOOKUP_OBJECT (maquette_ajout_modif_supp_offre, mod_sup_reservation, "mod_sup_reservation");
  GLADE_HOOKUP_OBJECT (maquette_ajout_modif_supp_offre, ajout_reservation, "ajout_reservation");

  return maquette_ajout_modif_supp_offre;
}

GtkWidget*
create_maquette_ajout_offre (void)
{
  GtkWidget *maquette_ajout_offre;
  GtkWidget *fixed2;
  GtkWidget *notebook1;
  GtkWidget *fixed3;
  GtkWidget *nom_hotel;
  GtkWidget *label11;
  GtkWidget *adresse_hotel;
  GtkWidget *label10;
  GtkWidget *label13;
  GtkWidget *label12;
  GtkWidget *tarif_adulte;
  GtkWidget *tarif_enfant;
  GtkWidget *label14;
  GtkObject *nombre_etoile_adj;
  GtkWidget *nombre_etoile;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkObject *ajout_de_jour_adj;
  GtkWidget *ajout_de_jour;
  GtkObject *ajout_a_jour_adj;
  GtkWidget *ajout_a_jour;
  GtkWidget *label19;
  GtkWidget *label17;
  GtkObject *ajout_de_mois_adj;
  GtkWidget *ajout_de_mois;
  GtkObject *ajout_de_annee_adj;
  GtkWidget *ajout_de_annee;
  GtkWidget *label18;
  GtkObject *ajout_a_mois_adj;
  GtkWidget *ajout_a_mois;
  GtkObject *ajout_a_annee_adj;
  GtkWidget *ajout_a_annee;
  GtkWidget *retour_ajout_hebergement;
  GtkWidget *ajouter_hebergement;
  GtkWidget *id_hotel;
  GtkWidget *saison;
  GtkWidget *type_chambre;
  GtkWidget *desc;
  GtkWidget *label92;
  GtkWidget *label7;
  GtkWidget *empty_notebook_page;
  GtkWidget *label8;
  GtkWidget *label9;

  maquette_ajout_offre = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (maquette_ajout_offre), _("maquette ajout hebergement"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (maquette_ajout_offre), fixed2);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed2), notebook1, 168, 88);
  gtk_widget_set_size_request (notebook1, 448, 368);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  nom_hotel = gtk_entry_new ();
  gtk_widget_show (nom_hotel);
  gtk_fixed_put (GTK_FIXED (fixed3), nom_hotel, 112, 16);
  gtk_widget_set_size_request (nom_hotel, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom_hotel), 8226);

  label11 = gtk_label_new (_("adresse"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed3), label11, 24, 64);
  gtk_widget_set_size_request (label11, 72, 24);

  adresse_hotel = gtk_entry_new ();
  gtk_widget_show (adresse_hotel);
  gtk_fixed_put (GTK_FIXED (fixed3), adresse_hotel, 112, 64);
  gtk_widget_set_size_request (adresse_hotel, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (adresse_hotel), 8226);

  label10 = gtk_label_new (_("nom de l'hotel"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 0, 16);
  gtk_widget_set_size_request (label10, 120, 32);

  label13 = gtk_label_new (_("tarif adulte"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 8, 112);
  gtk_widget_set_size_request (label13, 88, 16);

  label12 = gtk_label_new (_("tarif enfant"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed3), label12, 192, 112);
  gtk_widget_set_size_request (label12, 88, 16);

  tarif_adulte = gtk_entry_new ();
  gtk_widget_show (tarif_adulte);
  gtk_fixed_put (GTK_FIXED (fixed3), tarif_adulte, 96, 112);
  gtk_widget_set_size_request (tarif_adulte, 48, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (tarif_adulte), 8226);

  tarif_enfant = gtk_entry_new ();
  gtk_widget_show (tarif_enfant);
  gtk_fixed_put (GTK_FIXED (fixed3), tarif_enfant, 280, 112);
  gtk_widget_set_size_request (tarif_enfant, 48, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (tarif_enfant), 8226);

  label14 = gtk_label_new (_("saison"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 16, 152);
  gtk_widget_set_size_request (label14, 49, 17);

  nombre_etoile_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  nombre_etoile = gtk_spin_button_new (GTK_ADJUSTMENT (nombre_etoile_adj), 1, 0);
  gtk_widget_show (nombre_etoile);
  gtk_fixed_put (GTK_FIXED (fixed3), nombre_etoile, 320, 160);
  gtk_widget_set_size_request (nombre_etoile, 48, 24);

  label15 = gtk_label_new (_("nb etoile"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 224, 160);
  gtk_widget_set_size_request (label15, 88, 24);

  label16 = gtk_label_new (_("type de chambre"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 24, 200);
  gtk_widget_set_size_request (label16, 112, 16);

  ajout_de_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  ajout_de_jour = gtk_spin_button_new (GTK_ADJUSTMENT (ajout_de_jour_adj), 1, 0);
  gtk_widget_show (ajout_de_jour);
  gtk_fixed_put (GTK_FIXED (fixed3), ajout_de_jour, 32, 240);
  gtk_widget_set_size_request (ajout_de_jour, 48, 24);

  ajout_a_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  ajout_a_jour = gtk_spin_button_new (GTK_ADJUSTMENT (ajout_a_jour_adj), 1, 0);
  gtk_widget_show (ajout_a_jour);
  gtk_fixed_put (GTK_FIXED (fixed3), ajout_a_jour, 208, 240);
  gtk_widget_set_size_request (ajout_a_jour, 48, 24);

  label19 = gtk_label_new (_("ajouter\nune description"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 16, 288);
  gtk_widget_set_size_request (label19, 152, 40);

  label17 = gtk_label_new (_("De"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 0, 240);
  gtk_widget_set_size_request (label17, 49, 24);

  ajout_de_mois_adj = gtk_adjustment_new (1, 0, 12, 1, 10, 10);
  ajout_de_mois = gtk_spin_button_new (GTK_ADJUSTMENT (ajout_de_mois_adj), 1, 0);
  gtk_widget_show (ajout_de_mois);
  gtk_fixed_put (GTK_FIXED (fixed3), ajout_de_mois, 80, 240);
  gtk_widget_set_size_request (ajout_de_mois, 48, 24);

  ajout_de_annee_adj = gtk_adjustment_new (1, 2019, 2030, 1, 10, 10);
  ajout_de_annee = gtk_spin_button_new (GTK_ADJUSTMENT (ajout_de_annee_adj), 1, 0);
  gtk_widget_show (ajout_de_annee);
  gtk_fixed_put (GTK_FIXED (fixed3), ajout_de_annee, 128, 240);
  gtk_widget_set_size_request (ajout_de_annee, 60, 27);

  label18 = gtk_label_new (_("\303\240"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 176, 240);
  gtk_widget_set_size_request (label18, 49, 24);

  ajout_a_mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  ajout_a_mois = gtk_spin_button_new (GTK_ADJUSTMENT (ajout_a_mois_adj), 1, 0);
  gtk_widget_show (ajout_a_mois);
  gtk_fixed_put (GTK_FIXED (fixed3), ajout_a_mois, 256, 240);
  gtk_widget_set_size_request (ajout_a_mois, 48, 24);

  ajout_a_annee_adj = gtk_adjustment_new (1, 2019, 2030, 1, 10, 10);
  ajout_a_annee = gtk_spin_button_new (GTK_ADJUSTMENT (ajout_a_annee_adj), 1, 0);
  gtk_widget_show (ajout_a_annee);
  gtk_fixed_put (GTK_FIXED (fixed3), ajout_a_annee, 304, 240);
  gtk_widget_set_size_request (ajout_a_annee, 60, 27);

  retour_ajout_hebergement = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (retour_ajout_hebergement);
  gtk_fixed_put (GTK_FIXED (fixed3), retour_ajout_hebergement, 296, 304);
  gtk_widget_set_size_request (retour_ajout_hebergement, 66, 29);

  ajouter_hebergement = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (ajouter_hebergement);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter_hebergement, 296, 272);
  gtk_widget_set_size_request (ajouter_hebergement, 66, 29);

  id_hotel = gtk_entry_new ();
  gtk_widget_show (id_hotel);
  gtk_fixed_put (GTK_FIXED (fixed3), id_hotel, 272, 64);
  gtk_widget_set_size_request (id_hotel, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_hotel), 8226);

  saison = gtk_combo_box_entry_new_text ();
  gtk_widget_show (saison);
  gtk_fixed_put (GTK_FIXED (fixed3), saison, 72, 152);
  gtk_widget_set_size_request (saison, 133, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (saison), _("printemps"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (saison), _("hiver"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (saison), _("ete"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (saison), _("automne"));

  type_chambre = gtk_combo_box_entry_new_text ();
  gtk_widget_show (type_chambre);
  gtk_fixed_put (GTK_FIXED (fixed3), type_chambre, 144, 200);
  gtk_widget_set_size_request (type_chambre, 157, 21);
  gtk_combo_box_append_text (GTK_COMBO_BOX (type_chambre), _("individuelle"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (type_chambre), _("paire"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (type_chambre), _("suite"));

  desc = gtk_entry_new ();
  gtk_widget_show (desc);
  gtk_fixed_put (GTK_FIXED (fixed3), desc, 160, 272);
  gtk_widget_set_size_request (desc, 112, 72);
  gtk_entry_set_invisible_char (GTK_ENTRY (desc), 8226);

  label92 = gtk_label_new (_("identifiant:"));
  gtk_widget_show (label92);
  gtk_fixed_put (GTK_FIXED (fixed3), label92, 256, 40);
  gtk_widget_set_size_request (label92, 120, 24);

  label7 = gtk_label_new (_("hebergement"));
  gtk_widget_show (label7);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label7);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label8 = gtk_label_new (_("vol"));
  gtk_widget_show (label8);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label8);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label9 = gtk_label_new_with_mnemonic (_("location de voitures"));
  gtk_widget_show (label9);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label9);

  g_signal_connect ((gpointer) retour_ajout_hebergement, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_hebergement, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (maquette_ajout_offre, maquette_ajout_offre, "maquette_ajout_offre");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, nom_hotel, "nom_hotel");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, label11, "label11");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, adresse_hotel, "adresse_hotel");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, label10, "label10");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, label13, "label13");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, label12, "label12");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, tarif_adulte, "tarif_adulte");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, tarif_enfant, "tarif_enfant");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, label14, "label14");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, nombre_etoile, "nombre_etoile");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, label15, "label15");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, label16, "label16");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, ajout_de_jour, "ajout_de_jour");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, ajout_a_jour, "ajout_a_jour");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, label19, "label19");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, label17, "label17");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, ajout_de_mois, "ajout_de_mois");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, ajout_de_annee, "ajout_de_annee");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, label18, "label18");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, ajout_a_mois, "ajout_a_mois");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, ajout_a_annee, "ajout_a_annee");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, retour_ajout_hebergement, "retour_ajout_hebergement");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, ajouter_hebergement, "ajouter_hebergement");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, id_hotel, "id_hotel");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, saison, "saison");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, type_chambre, "type_chambre");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, desc, "desc");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, label92, "label92");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, label7, "label7");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, label8, "label8");
  GLADE_HOOKUP_OBJECT (maquette_ajout_offre, label9, "label9");

  return maquette_ajout_offre;
}

GtkWidget*
create_maquette_suppression_modification_offre (void)
{
  GtkWidget *maquette_suppression_modification_offre;
  GtkWidget *fixed4;
  GtkWidget *fixed6;
  GtkWidget *table1;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *fixed8;
  GtkWidget *label31;
  GtkWidget *fixed9;
  GtkWidget *fixed10;
  GtkWidget *label33;
  GtkWidget *label32;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkWidget *label40;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *modifier_hebergement;
  GtkWidget *supprimer_hebergement;
  GtkWidget *treeview_maquette_suppression_modification_offre;
  GtkWidget *identifiant_hotel;
  GtkWidget *label93;

  maquette_suppression_modification_offre = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (maquette_suppression_modification_offre), _("maquette suppression/modification offre"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (maquette_suppression_modification_offre), fixed4);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_fixed_put (GTK_FIXED (fixed4), fixed6, 504, 296);

  table1 = gtk_table_new (3, 8, FALSE);
  gtk_widget_show (table1);
  gtk_fixed_put (GTK_FIXED (fixed6), table1, 32, 48);
  gtk_widget_set_size_request (table1, 490, 202);

  label23 = gtk_label_new (_("nom\nhotel"));
  gtk_widget_show (label23);
  gtk_table_attach (GTK_TABLE (table1), label23, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label23, 62, 34);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);

  label24 = gtk_label_new (_("nb \netoile"));
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table1), label24, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label24, 51, 34);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  label25 = gtk_label_new (_("pension"));
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table1), label25, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  label26 = gtk_label_new (_("nb\nchambre"));
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table1), label26, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label26, 71, 34);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  label27 = gtk_label_new (_("type\nchambre"));
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table1), label27, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  label28 = gtk_label_new (_("saison"));
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table1), label28, 5, 6, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label28, 56, 17);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);

  label29 = gtk_label_new (_("tarif\nadulte"));
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table1), label29, 6, 7, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label29, 63, 34);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  label30 = gtk_label_new (_("tarif\nenfant"));
  gtk_widget_show (label30);
  gtk_table_attach (GTK_TABLE (table1), label30, 7, 8, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label30, 68, 34);
  gtk_misc_set_alignment (GTK_MISC (label30), 0, 0.5);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_table_attach (GTK_TABLE (table1), fixed8, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label31 = gtk_label_new (_("xxx"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed8), label31, 0, 56);
  gtk_widget_set_size_request (label31, 49, 17);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_table_attach (GTK_TABLE (table1), fixed9, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_fixed_put (GTK_FIXED (fixed9), fixed10, 40, 72);
  gtk_widget_set_size_request (fixed10, 50, 50);

  label33 = gtk_label_new (_("4"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed9), label33, 8, 56);
  gtk_widget_set_size_request (label33, 49, 17);

  label32 = gtk_label_new (_("yyy"));
  gtk_widget_show (label32);
  gtk_table_attach (GTK_TABLE (table1), label32, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label32), 0, 0.5);

  label34 = gtk_label_new (_("***"));
  gtk_widget_show (label34);
  gtk_table_attach (GTK_TABLE (table1), label34, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label34), 0, 0.5);

  label35 = gtk_label_new (_("****"));
  gtk_widget_show (label35);
  gtk_table_attach (GTK_TABLE (table1), label35, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label35), 0, 0.5);

  label36 = gtk_label_new (_("****"));
  gtk_widget_show (label36);
  gtk_table_attach (GTK_TABLE (table1), label36, 4, 5, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label36), 0, 0.5);

  label37 = gtk_label_new (_("****"));
  gtk_widget_show (label37);
  gtk_table_attach (GTK_TABLE (table1), label37, 5, 6, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label37), 0, 0.5);

  label38 = gtk_label_new (_("****"));
  gtk_widget_show (label38);
  gtk_table_attach (GTK_TABLE (table1), label38, 6, 7, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label38), 0, 0.5);

  label39 = gtk_label_new (_("****"));
  gtk_widget_show (label39);
  gtk_table_attach (GTK_TABLE (table1), label39, 7, 8, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label39), 0, 0.5);

  label40 = gtk_label_new (_("***"));
  gtk_widget_show (label40);
  gtk_table_attach (GTK_TABLE (table1), label40, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label40), 0, 0.5);

  label41 = gtk_label_new (_("****"));
  gtk_widget_show (label41);
  gtk_table_attach (GTK_TABLE (table1), label41, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label41), 0, 0.5);

  label42 = gtk_label_new (_("****"));
  gtk_widget_show (label42);
  gtk_table_attach (GTK_TABLE (table1), label42, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label42, 17, 17);
  gtk_misc_set_alignment (GTK_MISC (label42), 0, 0.5);

  label43 = gtk_label_new (_("***"));
  gtk_widget_show (label43);
  gtk_table_attach (GTK_TABLE (table1), label43, 4, 5, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label43), 0, 0.5);

  label44 = gtk_label_new (_("****"));
  gtk_widget_show (label44);
  gtk_table_attach (GTK_TABLE (table1), label44, 5, 6, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label44), 0, 0.5);

  label45 = gtk_label_new (_("******"));
  gtk_widget_show (label45);
  gtk_table_attach (GTK_TABLE (table1), label45, 6, 7, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label45), 0, 0.5);

  label46 = gtk_label_new (_("****"));
  gtk_widget_show (label46);
  gtk_table_attach (GTK_TABLE (table1), label46, 7, 8, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label46), 0, 0.5);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, "");
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobutton1, 544, 224);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, "");
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobutton2, 544, 144);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  modifier_hebergement = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (modifier_hebergement);
  gtk_fixed_put (GTK_FIXED (fixed6), modifier_hebergement, 592, 328);
  gtk_widget_set_size_request (modifier_hebergement, 96, 24);

  supprimer_hebergement = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (supprimer_hebergement);
  gtk_fixed_put (GTK_FIXED (fixed6), supprimer_hebergement, 592, 368);
  gtk_widget_set_size_request (supprimer_hebergement, 96, 24);

  treeview_maquette_suppression_modification_offre = gtk_tree_view_new ();
  gtk_widget_show (treeview_maquette_suppression_modification_offre);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview_maquette_suppression_modification_offre, 0, 8);
  gtk_widget_set_size_request (treeview_maquette_suppression_modification_offre, 300, 200);

  identifiant_hotel = gtk_entry_new ();
  gtk_widget_show (identifiant_hotel);
  gtk_fixed_put (GTK_FIXED (fixed6), identifiant_hotel, 448, 352);
  gtk_widget_set_size_request (identifiant_hotel, 128, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (identifiant_hotel), 8226);

  label93 = gtk_label_new (_("idetifiant hotel"));
  gtk_widget_show (label93);
  gtk_fixed_put (GTK_FIXED (fixed6), label93, 504, 296);
  gtk_widget_set_size_request (label93, 49, 17);

  g_signal_connect ((gpointer) modifier_hebergement, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_hebergement, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (maquette_suppression_modification_offre, maquette_suppression_modification_offre, "maquette_suppression_modification_offre");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, table1, "table1");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label23, "label23");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label24, "label24");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label25, "label25");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label26, "label26");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label27, "label27");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label28, "label28");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label29, "label29");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label30, "label30");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label31, "label31");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label33, "label33");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label32, "label32");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label34, "label34");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label35, "label35");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label36, "label36");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label37, "label37");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label38, "label38");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label39, "label39");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label40, "label40");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label41, "label41");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label42, "label42");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label43, "label43");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label44, "label44");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label45, "label45");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label46, "label46");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, modifier_hebergement, "modifier_hebergement");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, supprimer_hebergement, "supprimer_hebergement");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, treeview_maquette_suppression_modification_offre, "treeview_maquette_suppression_modification_offre");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, identifiant_hotel, "identifiant_hotel");
  GLADE_HOOKUP_OBJECT (maquette_suppression_modification_offre, label93, "label93");

  return maquette_suppression_modification_offre;
}

GtkWidget*
create_maquette_rechercher_hebergement (void)
{
  GtkWidget *maquette_rechercher_hebergement;
  GtkWidget *fixed11;
  GtkWidget *notebook3;
  GtkWidget *fixed12;
  GtkWidget *label50;
  GtkWidget *entry9;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkWidget *label51;
  GtkWidget *label52;
  GtkWidget *entry10;
  GtkWidget *entry11;
  GtkWidget *entry12;
  GtkWidget *label53;
  GtkWidget *label54;
  GtkWidget *label55;
  GtkWidget *rechercher_hebergement;
  GtkWidget *label47;
  GtkWidget *empty_notebook_page;
  GtkWidget *label48;
  GtkWidget *label49;

  maquette_rechercher_hebergement = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (maquette_rechercher_hebergement), _("maquette recherche hebergement"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (maquette_rechercher_hebergement), fixed11);

  notebook3 = gtk_notebook_new ();
  gtk_widget_show (notebook3);
  gtk_fixed_put (GTK_FIXED (fixed11), notebook3, 56, 104);
  gtk_widget_set_size_request (notebook3, 344, 328);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed12);

  label50 = gtk_label_new (_("destination"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed12), label50, 0, 40);
  gtk_widget_set_size_request (label50, 96, 24);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed12), entry9, 96, 40);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  spinbutton4_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton4, 56, 88);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  spinbutton5_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton5, 184, 88);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  label51 = gtk_label_new (_("De"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed12), label51, 8, 88);
  gtk_widget_set_size_request (label51, 48, 24);

  label52 = gtk_label_new (_("\303\240"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed12), label52, 136, 88);
  gtk_widget_set_size_request (label52, 48, 32);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed12), entry10, 152, 136);
  gtk_widget_set_size_request (entry10, 80, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed12), entry11, 152, 176);
  gtk_widget_set_size_request (entry11, 80, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed12), entry12, 152, 208);
  gtk_widget_set_size_request (entry12, 80, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  label53 = gtk_label_new (_("nombre de chambre"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed12), label53, 8, 136);
  gtk_widget_set_size_request (label53, 136, 24);

  label54 = gtk_label_new (_("nombre d'adultes"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed12), label54, 16, 176);
  gtk_widget_set_size_request (label54, 128, 24);

  label55 = gtk_label_new (_("nombre d'enfants"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed12), label55, 8, 208);
  gtk_widget_set_size_request (label55, 144, 24);

  rechercher_hebergement = gtk_button_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (rechercher_hebergement);
  gtk_fixed_put (GTK_FIXED (fixed12), rechercher_hebergement, 248, 256);
  gtk_widget_set_size_request (rechercher_hebergement, 88, 29);

  label47 = gtk_label_new (_("hebergement"));
  gtk_widget_show (label47);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 0), label47);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook3), empty_notebook_page);

  label48 = gtk_label_new (_("vol"));
  gtk_widget_show (label48);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 1), label48);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook3), empty_notebook_page);

  label49 = gtk_label_new (_("location"));
  gtk_widget_show (label49);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 2), label49);

  g_signal_connect ((gpointer) rechercher_hebergement, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (maquette_rechercher_hebergement, maquette_rechercher_hebergement, "maquette_rechercher_hebergement");
  GLADE_HOOKUP_OBJECT (maquette_rechercher_hebergement, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (maquette_rechercher_hebergement, notebook3, "notebook3");
  GLADE_HOOKUP_OBJECT (maquette_rechercher_hebergement, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (maquette_rechercher_hebergement, label50, "label50");
  GLADE_HOOKUP_OBJECT (maquette_rechercher_hebergement, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (maquette_rechercher_hebergement, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (maquette_rechercher_hebergement, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (maquette_rechercher_hebergement, label51, "label51");
  GLADE_HOOKUP_OBJECT (maquette_rechercher_hebergement, label52, "label52");
  GLADE_HOOKUP_OBJECT (maquette_rechercher_hebergement, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (maquette_rechercher_hebergement, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (maquette_rechercher_hebergement, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (maquette_rechercher_hebergement, label53, "label53");
  GLADE_HOOKUP_OBJECT (maquette_rechercher_hebergement, label54, "label54");
  GLADE_HOOKUP_OBJECT (maquette_rechercher_hebergement, label55, "label55");
  GLADE_HOOKUP_OBJECT (maquette_rechercher_hebergement, rechercher_hebergement, "rechercher_hebergement");
  GLADE_HOOKUP_OBJECT (maquette_rechercher_hebergement, label47, "label47");
  GLADE_HOOKUP_OBJECT (maquette_rechercher_hebergement, label48, "label48");
  GLADE_HOOKUP_OBJECT (maquette_rechercher_hebergement, label49, "label49");

  return maquette_rechercher_hebergement;
}

GtkWidget*
create_maquette_liste_resultat (void)
{
  GtkWidget *maquette_liste_resultat;
  GtkWidget *fixed13;
  GtkWidget *table2;
  GtkWidget *label56;
  GtkWidget *label57;
  GtkWidget *label58;
  GtkWidget *label59;
  GtkWidget *label60;
  GtkWidget *label61;
  GtkWidget *label62;
  GtkWidget *label63;
  GtkWidget *label64;
  GtkWidget *label65;
  GtkWidget *label66;
  GtkWidget *label67;
  GtkWidget *label68;
  GtkWidget *label69;
  GtkWidget *label70;
  GtkWidget *radiobutton3;
  GSList *radiobutton3_group = NULL;
  GtkWidget *radiobutton4;
  GtkWidget *treeview_maquette_liste_resultat;
  GtkWidget *reserver_hebergement;

  maquette_liste_resultat = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (maquette_liste_resultat), _("maquette liste resultat"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (maquette_liste_resultat), fixed13);

  table2 = gtk_table_new (3, 5, FALSE);
  gtk_widget_show (table2);
  gtk_fixed_put (GTK_FIXED (fixed13), table2, 72, 56);
  gtk_widget_set_size_request (table2, 80, 48);

  label56 = gtk_label_new (_("nom hotel"));
  gtk_widget_show (label56);
  gtk_table_attach (GTK_TABLE (table2), label56, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label56, 99, 22);
  gtk_misc_set_alignment (GTK_MISC (label56), 0, 0.5);

  label57 = gtk_label_new (_("Pension"));
  gtk_widget_show (label57);
  gtk_table_attach (GTK_TABLE (table2), label57, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label57, 79, 24);
  gtk_misc_set_alignment (GTK_MISC (label57), 0, 0.5);

  label58 = gtk_label_new (_("tarif\nfinal"));
  gtk_widget_show (label58);
  gtk_table_attach (GTK_TABLE (table2), label58, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label58, 45, 42);
  gtk_misc_set_alignment (GTK_MISC (label58), 0, 0.5);

  label59 = gtk_label_new (_("type de\nchambre"));
  gtk_widget_show (label59);
  gtk_table_attach (GTK_TABLE (table2), label59, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label59, 67, 45);
  gtk_misc_set_alignment (GTK_MISC (label59), 0, 0.5);

  label60 = gtk_label_new (_("nb etoile"));
  gtk_widget_show (label60);
  gtk_table_attach (GTK_TABLE (table2), label60, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label60, 73, 28);
  gtk_misc_set_alignment (GTK_MISC (label60), 0, 0.5);

  label61 = gtk_label_new (_("****"));
  gtk_widget_show (label61);
  gtk_table_attach (GTK_TABLE (table2), label61, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label61, -1, 30);
  gtk_misc_set_alignment (GTK_MISC (label61), 0, 0.5);

  label62 = gtk_label_new (_("*****"));
  gtk_widget_show (label62);
  gtk_table_attach (GTK_TABLE (table2), label62, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label62, -1, 30);
  gtk_misc_set_alignment (GTK_MISC (label62), 0, 0.5);

  label63 = gtk_label_new (_("***"));
  gtk_widget_show (label63);
  gtk_table_attach (GTK_TABLE (table2), label63, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label63, -1, 30);
  gtk_misc_set_alignment (GTK_MISC (label63), 0, 0.5);

  label64 = gtk_label_new (_("******"));
  gtk_widget_show (label64);
  gtk_table_attach (GTK_TABLE (table2), label64, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label64, -1, 30);
  gtk_misc_set_alignment (GTK_MISC (label64), 0, 0.5);

  label65 = gtk_label_new (_("**"));
  gtk_widget_show (label65);
  gtk_table_attach (GTK_TABLE (table2), label65, 4, 5, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label65, -1, 30);
  gtk_misc_set_alignment (GTK_MISC (label65), 0, 0.5);

  label66 = gtk_label_new (_("*********"));
  gtk_widget_show (label66);
  gtk_table_attach (GTK_TABLE (table2), label66, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label66, -1, 30);
  gtk_misc_set_alignment (GTK_MISC (label66), 0, 0.5);

  label67 = gtk_label_new (_("****"));
  gtk_widget_show (label67);
  gtk_table_attach (GTK_TABLE (table2), label67, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label67, -1, 30);
  gtk_misc_set_alignment (GTK_MISC (label67), 0, 0.5);

  label68 = gtk_label_new (_("**"));
  gtk_widget_show (label68);
  gtk_table_attach (GTK_TABLE (table2), label68, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label68, -1, 30);
  gtk_misc_set_alignment (GTK_MISC (label68), 0, 0.5);

  label69 = gtk_label_new (_("******"));
  gtk_widget_show (label69);
  gtk_table_attach (GTK_TABLE (table2), label69, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label69, -1, 30);
  gtk_misc_set_alignment (GTK_MISC (label69), 0, 0.5);

  label70 = gtk_label_new (_("***"));
  gtk_widget_show (label70);
  gtk_table_attach (GTK_TABLE (table2), label70, 4, 5, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label70, 21, 30);
  gtk_misc_set_alignment (GTK_MISC (label70), 0, 0.5);

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, "");
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed13), radiobutton3, 440, 96);
  gtk_widget_set_size_request (radiobutton3, 32, 16);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, "");
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed13), radiobutton4, 440, 128);
  gtk_widget_set_size_request (radiobutton4, 32, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  treeview_maquette_liste_resultat = gtk_tree_view_new ();
  gtk_widget_show (treeview_maquette_liste_resultat);
  gtk_fixed_put (GTK_FIXED (fixed13), treeview_maquette_liste_resultat, 80, 192);
  gtk_widget_set_size_request (treeview_maquette_liste_resultat, 300, 200);

  reserver_hebergement = gtk_button_new_with_mnemonic (_("Reserver"));
  gtk_widget_show (reserver_hebergement);
  gtk_fixed_put (GTK_FIXED (fixed13), reserver_hebergement, 432, 224);
  gtk_widget_set_size_request (reserver_hebergement, 120, 72);

  g_signal_connect ((gpointer) reserver_hebergement, "clicked",
                    G_CALLBACK (on__clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (maquette_liste_resultat, maquette_liste_resultat, "maquette_liste_resultat");
  GLADE_HOOKUP_OBJECT (maquette_liste_resultat, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (maquette_liste_resultat, table2, "table2");
  GLADE_HOOKUP_OBJECT (maquette_liste_resultat, label56, "label56");
  GLADE_HOOKUP_OBJECT (maquette_liste_resultat, label57, "label57");
  GLADE_HOOKUP_OBJECT (maquette_liste_resultat, label58, "label58");
  GLADE_HOOKUP_OBJECT (maquette_liste_resultat, label59, "label59");
  GLADE_HOOKUP_OBJECT (maquette_liste_resultat, label60, "label60");
  GLADE_HOOKUP_OBJECT (maquette_liste_resultat, label61, "label61");
  GLADE_HOOKUP_OBJECT (maquette_liste_resultat, label62, "label62");
  GLADE_HOOKUP_OBJECT (maquette_liste_resultat, label63, "label63");
  GLADE_HOOKUP_OBJECT (maquette_liste_resultat, label64, "label64");
  GLADE_HOOKUP_OBJECT (maquette_liste_resultat, label65, "label65");
  GLADE_HOOKUP_OBJECT (maquette_liste_resultat, label66, "label66");
  GLADE_HOOKUP_OBJECT (maquette_liste_resultat, label67, "label67");
  GLADE_HOOKUP_OBJECT (maquette_liste_resultat, label68, "label68");
  GLADE_HOOKUP_OBJECT (maquette_liste_resultat, label69, "label69");
  GLADE_HOOKUP_OBJECT (maquette_liste_resultat, label70, "label70");
  GLADE_HOOKUP_OBJECT (maquette_liste_resultat, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (maquette_liste_resultat, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (maquette_liste_resultat, treeview_maquette_liste_resultat, "treeview_maquette_liste_resultat");
  GLADE_HOOKUP_OBJECT (maquette_liste_resultat, reserver_hebergement, "reserver_hebergement");

  return maquette_liste_resultat;
}

GtkWidget*
create_message_d_erreur_recherche (void)
{
  GtkWidget *message_d_erreur_recherche;
  GtkWidget *fixed14;
  GtkWidget *label71;
  GtkWidget *retour_resultat;

  message_d_erreur_recherche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (message_d_erreur_recherche), _("message d'erreur recherche"));

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (message_d_erreur_recherche), fixed14);

  label71 = gtk_label_new (_("aucun resultat \ntrouv\303\251"));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed14), label71, 128, 88);
  gtk_widget_set_size_request (label71, 176, 72);
  gtk_label_set_justify (GTK_LABEL (label71), GTK_JUSTIFY_CENTER);

  retour_resultat = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (retour_resultat);
  gtk_fixed_put (GTK_FIXED (fixed14), retour_resultat, 256, 208);
  gtk_widget_set_size_request (retour_resultat, 104, 40);

  g_signal_connect ((gpointer) retour_resultat, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (message_d_erreur_recherche, message_d_erreur_recherche, "message_d_erreur_recherche");
  GLADE_HOOKUP_OBJECT (message_d_erreur_recherche, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (message_d_erreur_recherche, label71, "label71");
  GLADE_HOOKUP_OBJECT (message_d_erreur_recherche, retour_resultat, "retour_resultat");

  return message_d_erreur_recherche;
}

GtkWidget*
create_maquette_confirmation (void)
{
  GtkWidget *maquette_confirmation;
  GtkWidget *fixed15;
  GtkWidget *label72;
  GtkWidget *label73;
  GtkWidget *entry13;
  GtkWidget *entry14;
  GtkWidget *label74;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkWidget *label75;
  GtkWidget *entry15;
  GtkWidget *button10;
  GtkWidget *button11;

  maquette_confirmation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (maquette_confirmation), _("maquette confirmation"));

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (maquette_confirmation), fixed15);

  label72 = gtk_label_new (_("numero de carte"));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed15), label72, 8, 24);
  gtk_widget_set_size_request (label72, 136, 32);

  label73 = gtk_label_new (_("nom titulaire de la carte"));
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed15), label73, 8, 72);
  gtk_widget_set_size_request (label73, 184, 24);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed15), entry13, 192, 32);
  gtk_widget_set_size_request (entry13, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  entry14 = gtk_entry_new ();
  gtk_widget_show (entry14);
  gtk_fixed_put (GTK_FIXED (fixed15), entry14, 192, 72);
  gtk_widget_set_size_request (entry14, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 8226);

  label74 = gtk_label_new (_("Date d'expiration"));
  gtk_widget_show (label74);
  gtk_fixed_put (GTK_FIXED (fixed15), label74, 16, 120);
  gtk_widget_set_size_request (label74, 136, 32);

  spinbutton6_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed15), spinbutton6, 192, 120);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  spinbutton7_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed15), spinbutton7, 280, 120);
  gtk_widget_set_size_request (spinbutton7, 60, 27);

  label75 = gtk_label_new (_("code de securite"));
  gtk_widget_show (label75);
  gtk_fixed_put (GTK_FIXED (fixed15), label75, 32, 176);
  gtk_widget_set_size_request (label75, 128, 24);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_fixed_put (GTK_FIXED (fixed15), entry15, 184, 176);
  gtk_widget_set_size_request (entry15, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);

  button10 = gtk_button_new_with_mnemonic (_("generer facture"));
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed15), button10, 56, 240);
  gtk_widget_set_size_request (button10, 128, 32);

  button11 = gtk_button_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed15), button11, 264, 240);
  gtk_widget_set_size_request (button11, 88, 32);

  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_button10_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (maquette_confirmation, maquette_confirmation, "maquette_confirmation");
  GLADE_HOOKUP_OBJECT (maquette_confirmation, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (maquette_confirmation, label72, "label72");
  GLADE_HOOKUP_OBJECT (maquette_confirmation, label73, "label73");
  GLADE_HOOKUP_OBJECT (maquette_confirmation, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (maquette_confirmation, entry14, "entry14");
  GLADE_HOOKUP_OBJECT (maquette_confirmation, label74, "label74");
  GLADE_HOOKUP_OBJECT (maquette_confirmation, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (maquette_confirmation, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (maquette_confirmation, label75, "label75");
  GLADE_HOOKUP_OBJECT (maquette_confirmation, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (maquette_confirmation, button10, "button10");
  GLADE_HOOKUP_OBJECT (maquette_confirmation, button11, "button11");

  return maquette_confirmation;
}

GtkWidget*
create_maquette_mod_sup_reservation (void)
{
  GtkWidget *maquette_mod_sup_reservation;
  GtkWidget *fixed17;
  GtkWidget *treeview2;
  GtkWidget *label91;
  GtkWidget *reservation_id_reservatio;
  GtkWidget *button_modifier_reservation;
  GtkWidget *button_supprimer_reservation;

  maquette_mod_sup_reservation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (maquette_mod_sup_reservation), _("maquette reservation"));

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (maquette_mod_sup_reservation), fixed17);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed17), treeview2, 56, 24);
  gtk_widget_set_size_request (treeview2, 300, 200);

  label91 = gtk_label_new (_("idreservation"));
  gtk_widget_show (label91);
  gtk_fixed_put (GTK_FIXED (fixed17), label91, 64, 296);
  gtk_widget_set_size_request (label91, 112, 32);

  reservation_id_reservatio = gtk_entry_new ();
  gtk_widget_show (reservation_id_reservatio);
  gtk_fixed_put (GTK_FIXED (fixed17), reservation_id_reservatio, 176, 304);
  gtk_widget_set_size_request (reservation_id_reservatio, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (reservation_id_reservatio), 8226);

  button_modifier_reservation = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (button_modifier_reservation);
  gtk_fixed_put (GTK_FIXED (fixed17), button_modifier_reservation, 368, 312);
  gtk_widget_set_size_request (button_modifier_reservation, 88, 32);

  button_supprimer_reservation = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (button_supprimer_reservation);
  gtk_fixed_put (GTK_FIXED (fixed17), button_supprimer_reservation, 368, 360);
  gtk_widget_set_size_request (button_supprimer_reservation, 88, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (maquette_mod_sup_reservation, maquette_mod_sup_reservation, "maquette_mod_sup_reservation");
  GLADE_HOOKUP_OBJECT (maquette_mod_sup_reservation, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (maquette_mod_sup_reservation, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (maquette_mod_sup_reservation, label91, "label91");
  GLADE_HOOKUP_OBJECT (maquette_mod_sup_reservation, reservation_id_reservatio, "reservation_id_reservatio");
  GLADE_HOOKUP_OBJECT (maquette_mod_sup_reservation, button_modifier_reservation, "button_modifier_reservation");
  GLADE_HOOKUP_OBJECT (maquette_mod_sup_reservation, button_supprimer_reservation, "button_supprimer_reservation");

  return maquette_mod_sup_reservation;
}

GtkWidget*
create_maquette_liste_hotel (void)
{
  GtkWidget *maquette_liste_hotel;
  GtkWidget *fixed18;
  GtkWidget *treeview_maquette_liste_hotel;
  GtkWidget *button_liste_hotel;

  maquette_liste_hotel = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (maquette_liste_hotel), _("maquette liste hotel"));

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_container_add (GTK_CONTAINER (maquette_liste_hotel), fixed18);

  treeview_maquette_liste_hotel = gtk_tree_view_new ();
  gtk_widget_show (treeview_maquette_liste_hotel);
  gtk_fixed_put (GTK_FIXED (fixed18), treeview_maquette_liste_hotel, 48, 16);
  gtk_widget_set_size_request (treeview_maquette_liste_hotel, 300, 200);

  button_liste_hotel = gtk_button_new_with_mnemonic (_("rechercher"));
  gtk_widget_show (button_liste_hotel);
  gtk_fixed_put (GTK_FIXED (fixed18), button_liste_hotel, 280, 256);
  gtk_widget_set_size_request (button_liste_hotel, 88, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (maquette_liste_hotel, maquette_liste_hotel, "maquette_liste_hotel");
  GLADE_HOOKUP_OBJECT (maquette_liste_hotel, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (maquette_liste_hotel, treeview_maquette_liste_hotel, "treeview_maquette_liste_hotel");
  GLADE_HOOKUP_OBJECT (maquette_liste_hotel, button_liste_hotel, "button_liste_hotel");

  return maquette_liste_hotel;
}

