/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_maquette_ajout_modif_supp_offre (void);
GtkWidget* create_maquette_ajout_offre (void);
GtkWidget* create_maquette_suppression_modification_offre (void);
GtkWidget* create_maquette_rechercher_hebergement (void);
GtkWidget* create_maquette_liste_resultat (void);
GtkWidget* create_message_d_erreur_recherche (void);
GtkWidget* create_maquette_confirmation (void);
GtkWidget* create_maquette_mod_sup_reservation (void);
GtkWidget* create_maquette_liste_hotel (void);
