/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_auth (void);
GtkWidget* create_ajEspaceAd (void);
GtkWidget* create_GestioncompteAdmin (void);
GtkWidget* create_Ajout_Employe (void);
GtkWidget* create_Modifier_Employe (void);
GtkWidget* create_Modifier_Client (void);
GtkWidget* create_GestionClients (void);
GtkWidget* create_Recherche (void);
GtkWidget* create_Espace_Emp (void);
GtkWidget* create_Ajout_client (void);
GtkWidget* create_Ajout_Admin (void);
GtkWidget* create_EspaceCli (void);
GtkWidget* create_GestionEmp (void);
GtkWidget* create_fgDevisWindow (void);
GtkWidget* create_fgWindowRechercheD (void);
GtkWidget* create_fgFactureWindow (void);
GtkWidget* create_fgWindowRechercheF (void);
GtkWidget* create_fgDialogPaiement (void);
GtkWidget* create_dialog3 (void);
GtkWidget* create_Catalogue (void);
GtkWidget* create_mcRechercheVoitureClient (void);
GtkWidget* create_mcListeDesVoituresClient (void);
GtkWidget* create_mcAjoutModificationSupressionVoiture (void);
GtkWidget* create_mcAjouterVoiture (void);
GtkWidget* create_mcModificationVoiture (void);
GtkWidget* create_jbCherchervol (void);
GtkWidget* create_jbListevolallsimpleclient (void);
GtkWidget* create_jbListevolallretclient12 (void);
GtkWidget* create_jbListevolAllretemploye (void);
GtkWidget* create_jbListevolallsimpleemploye (void);
GtkWidget* create_jbListevolajoutempl (void);
GtkWidget* create_jbAjoutemploi12 (void);
