/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_auth (void)
{
  GtkWidget *auth;
  GtkWidget *fixed1;
  GtkWidget *ajLogin;
  GtkWidget *ajPass;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label1;
  GtkWidget *ajConnect;
  GtkWidget *ajErrAuth;

  auth = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (auth), 1);
  gtk_window_set_title (GTK_WINDOW (auth), _("Authentification"));
  gtk_window_set_default_size (GTK_WINDOW (auth), 600, 300);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (auth), fixed1);

  ajLogin = gtk_entry_new ();
  gtk_widget_show (ajLogin);
  gtk_fixed_put (GTK_FIXED (fixed1), ajLogin, 304, 144);
  gtk_widget_set_size_request (ajLogin, 160, 27);
  gtk_entry_set_max_length (GTK_ENTRY (ajLogin), 10);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajLogin), 8226);

  ajPass = gtk_entry_new ();
  gtk_widget_show (ajPass);
  gtk_fixed_put (GTK_FIXED (fixed1), ajPass, 304, 192);
  gtk_widget_set_size_request (ajPass, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (ajPass), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajPass), 8226);

  label2 = gtk_label_new (_("Login :"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 200, 136);
  gtk_widget_set_size_request (label2, 72, 40);

  label3 = gtk_label_new (_("mot de passe :"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 168, 192);
  gtk_widget_set_size_request (label3, 128, 32);

  label1 = gtk_label_new (_("Authentification"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 288, 32);
  gtk_widget_set_size_request (label1, 184, 64);

  ajConnect = gtk_button_new_with_mnemonic (_("se connecter"));
  gtk_widget_show (ajConnect);
  gtk_fixed_put (GTK_FIXED (fixed1), ajConnect, 312, 264);
  gtk_widget_set_size_request (ajConnect, 128, 48);

  ajErrAuth = gtk_label_new ("");
  gtk_widget_show (ajErrAuth);
  gtk_fixed_put (GTK_FIXED (fixed1), ajErrAuth, 8, 96);
  gtk_widget_set_size_request (ajErrAuth, 696, 32);

  g_signal_connect ((gpointer) ajConnect, "clicked",
                    G_CALLBACK (on_ajConnect_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (auth, auth, "auth");
  GLADE_HOOKUP_OBJECT (auth, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (auth, ajLogin, "ajLogin");
  GLADE_HOOKUP_OBJECT (auth, ajPass, "ajPass");
  GLADE_HOOKUP_OBJECT (auth, label2, "label2");
  GLADE_HOOKUP_OBJECT (auth, label3, "label3");
  GLADE_HOOKUP_OBJECT (auth, label1, "label1");
  GLADE_HOOKUP_OBJECT (auth, ajConnect, "ajConnect");
  GLADE_HOOKUP_OBJECT (auth, ajErrAuth, "ajErrAuth");

  return auth;
}

GtkWidget*
create_ajEspaceAd (void)
{
  GtkWidget *ajEspaceAd;
  GtkWidget *fixed2;
  GtkWidget *label4;
  GtkWidget *ajGestionCli;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label112;
  GtkWidget *ajRecherche;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label113;
  GtkWidget *ajConsRec;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label114;
  GtkWidget *ajGestionFact;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label115;
  GtkWidget *ajGestionService;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label116;
  GtkWidget *ajGestionCompteAdm;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label110;
  GtkWidget *ajGestionEmp;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label111;

  ajEspaceAd = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajEspaceAd), _("Espace Admin"));
  gtk_window_set_position (GTK_WINDOW (ajEspaceAd), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (ajEspaceAd), 500, 800);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (ajEspaceAd), fixed2);
  gtk_widget_set_size_request (fixed2, 552, 656);

  label4 = gtk_label_new (_("Espace Admin"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 336, 24);
  gtk_widget_set_size_request (label4, 184, 56);

  ajGestionCli = gtk_button_new ();
  gtk_widget_show (ajGestionCli);
  gtk_fixed_put (GTK_FIXED (fixed2), ajGestionCli, 328, 280);
  gtk_widget_set_size_request (ajGestionCli, 216, 64);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (ajGestionCli), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label112 = gtk_label_new_with_mnemonic (_("Gestion des clients"));
  gtk_widget_show (label112);
  gtk_box_pack_start (GTK_BOX (hbox3), label112, FALSE, FALSE, 0);

  ajRecherche = gtk_button_new ();
  gtk_widget_show (ajRecherche);
  gtk_fixed_put (GTK_FIXED (fixed2), ajRecherche, 328, 352);
  gtk_widget_set_size_request (ajRecherche, 216, 64);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (ajRecherche), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label113 = gtk_label_new_with_mnemonic (_("Recherche"));
  gtk_widget_show (label113);
  gtk_box_pack_start (GTK_BOX (hbox4), label113, FALSE, FALSE, 0);

  ajConsRec = gtk_button_new ();
  gtk_widget_show (ajConsRec);
  gtk_fixed_put (GTK_FIXED (fixed2), ajConsRec, 320, 424);
  gtk_widget_set_size_request (ajConsRec, 232, 88);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (ajConsRec), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label114 = gtk_label_new_with_mnemonic (_("Consultation des r\303\251clamations"));
  gtk_widget_show (label114);
  gtk_box_pack_start (GTK_BOX (hbox5), label114, FALSE, FALSE, 0);

  ajGestionFact = gtk_button_new ();
  gtk_widget_show (ajGestionFact);
  gtk_fixed_put (GTK_FIXED (fixed2), ajGestionFact, 344, 520);
  gtk_widget_set_size_request (ajGestionFact, 176, 56);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (ajGestionFact), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-page-setup", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label115 = gtk_label_new_with_mnemonic (_("Gestion Facture"));
  gtk_widget_show (label115);
  gtk_box_pack_start (GTK_BOX (hbox6), label115, FALSE, FALSE, 0);

  ajGestionService = gtk_button_new ();
  gtk_widget_show (ajGestionService);
  gtk_fixed_put (GTK_FIXED (fixed2), ajGestionService, 320, 592);
  gtk_widget_set_size_request (ajGestionService, 224, 64);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (ajGestionService), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-select-color", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label116 = gtk_label_new_with_mnemonic (_("Gestion des services"));
  gtk_widget_show (label116);
  gtk_box_pack_start (GTK_BOX (hbox7), label116, FALSE, FALSE, 0);

  ajGestionCompteAdm = gtk_button_new ();
  gtk_widget_show (ajGestionCompteAdm);
  gtk_fixed_put (GTK_FIXED (fixed2), ajGestionCompteAdm, 304, 104);
  gtk_widget_set_size_request (ajGestionCompteAdm, 248, 64);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajGestionCompteAdm), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label110 = gtk_label_new_with_mnemonic (_("Gestion du compte admin"));
  gtk_widget_show (label110);
  gtk_box_pack_start (GTK_BOX (hbox1), label110, FALSE, FALSE, 0);

  ajGestionEmp = gtk_button_new ();
  gtk_widget_show (ajGestionEmp);
  gtk_fixed_put (GTK_FIXED (fixed2), ajGestionEmp, 336, 192);
  gtk_widget_set_size_request (ajGestionEmp, 192, 64);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (ajGestionEmp), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label111 = gtk_label_new_with_mnemonic (_("Gestion des employ\303\251s"));
  gtk_widget_show (label111);
  gtk_box_pack_start (GTK_BOX (hbox2), label111, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) ajGestionCompteAdm, "clicked",
                    G_CALLBACK (on_ajGestionCompteAdm_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajGestionEmp, "clicked",
                    G_CALLBACK (on_ajGestionEmp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajEspaceAd, ajEspaceAd, "ajEspaceAd");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, label4, "label4");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, ajGestionCli, "ajGestionCli");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, image3, "image3");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, label112, "label112");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, ajRecherche, "ajRecherche");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, image4, "image4");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, label113, "label113");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, ajConsRec, "ajConsRec");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, image5, "image5");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, label114, "label114");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, ajGestionFact, "ajGestionFact");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, image6, "image6");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, label115, "label115");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, ajGestionService, "ajGestionService");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, image7, "image7");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, label116, "label116");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, ajGestionCompteAdm, "ajGestionCompteAdm");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, image1, "image1");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, label110, "label110");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, ajGestionEmp, "ajGestionEmp");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, image2, "image2");
  GLADE_HOOKUP_OBJECT (ajEspaceAd, label111, "label111");

  return ajEspaceAd;
}

GtkWidget*
create_Gestion_compteAdmin (void)
{
  GtkWidget *Gestion_compteAdmin;
  GtkWidget *fixed3;
  GtkWidget *textview1;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *ajNomAdm;
  GtkWidget *ajPrenomAdm;
  GtkWidget *label8;
  GtkWidget *ajIdAdm;
  GtkWidget *label9;
  GtkWidget *ajRoleAdm;
  GtkWidget *label10;
  GtkWidget *ajCinAdm;
  GtkWidget *label11;
  GtkWidget *ajMailAdm;
  GtkWidget *label12;
  GtkWidget *ajAdressAdm;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *ajLoginAdm;
  GtkWidget *ajPassAdm;
  GtkWidget *ajPhoneAdm;
  GtkWidget *label7;
  GtkWidget *ajSuppCompteAdm;
  GtkWidget *ajModifInfoAdm;
  GtkWidget *ajAjoutAdmn;

  Gestion_compteAdmin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gestion_compteAdmin), _("Gestion du Compte Admin"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Gestion_compteAdmin), fixed3);
  gtk_widget_set_size_request (fixed3, 840, 656);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_fixed_put (GTK_FIXED (fixed3), textview1, 24, 120);
  gtk_widget_set_size_request (textview1, 360, 448);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview1)), _("Nom:x\n\nPrenom:Y\n\nIdentifiant:fy1587\n\nmot de passe:*****\n\n"), -1);

  label5 = gtk_label_new (_("Gestion du compte admin"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed3), label5, 320, 0);
  gtk_widget_set_size_request (label5, 232, 72);

  label6 = gtk_label_new (_("information de l'admin :"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed3), label6, 80, 72);
  gtk_widget_set_size_request (label6, 200, 40);

  ajNomAdm = gtk_entry_new ();
  gtk_widget_show (ajNomAdm);
  gtk_fixed_put (GTK_FIXED (fixed3), ajNomAdm, 504, 136);
  gtk_widget_set_size_request (ajNomAdm, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajNomAdm), 8226);

  ajPrenomAdm = gtk_entry_new ();
  gtk_widget_show (ajPrenomAdm);
  gtk_fixed_put (GTK_FIXED (fixed3), ajPrenomAdm, 504, 176);
  gtk_widget_set_size_request (ajPrenomAdm, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajPrenomAdm), 8226);

  label8 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed3), label8, 424, 168);
  gtk_widget_set_size_request (label8, 80, 32);

  ajIdAdm = gtk_entry_new ();
  gtk_widget_show (ajIdAdm);
  gtk_fixed_put (GTK_FIXED (fixed3), ajIdAdm, 504, 216);
  gtk_widget_set_size_request (ajIdAdm, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (ajIdAdm), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajIdAdm), 8226);

  label9 = gtk_label_new (_("identifiant :"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed3), label9, 416, 208);
  gtk_widget_set_size_request (label9, 80, 32);

  ajRoleAdm = gtk_entry_new ();
  gtk_widget_show (ajRoleAdm);
  gtk_fixed_put (GTK_FIXED (fixed3), ajRoleAdm, 504, 248);
  gtk_widget_set_size_request (ajRoleAdm, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajRoleAdm), 8226);

  label10 = gtk_label_new (_("role :"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 424, 248);
  gtk_widget_set_size_request (label10, 80, 32);

  ajCinAdm = gtk_entry_new ();
  gtk_widget_show (ajCinAdm);
  gtk_fixed_put (GTK_FIXED (fixed3), ajCinAdm, 504, 280);
  gtk_widget_set_size_request (ajCinAdm, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajCinAdm), 8226);

  label11 = gtk_label_new (_("cin :"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed3), label11, 424, 280);
  gtk_widget_set_size_request (label11, 80, 32);

  ajMailAdm = gtk_entry_new ();
  gtk_widget_show (ajMailAdm);
  gtk_fixed_put (GTK_FIXED (fixed3), ajMailAdm, 504, 312);
  gtk_widget_set_size_request (ajMailAdm, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajMailAdm), 8226);

  label12 = gtk_label_new (_("E-mail :"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed3), label12, 424, 312);
  gtk_widget_set_size_request (label12, 80, 32);

  ajAdressAdm = gtk_entry_new ();
  gtk_widget_show (ajAdressAdm);
  gtk_fixed_put (GTK_FIXED (fixed3), ajAdressAdm, 504, 344);
  gtk_widget_set_size_request (ajAdressAdm, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajAdressAdm), 8226);

  label13 = gtk_label_new (_("adresse :"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 424, 344);
  gtk_widget_set_size_request (label13, 80, 32);

  label14 = gtk_label_new (_("login :"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 424, 376);
  gtk_widget_set_size_request (label14, 80, 32);

  label15 = gtk_label_new (_("password :"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 424, 408);
  gtk_widget_set_size_request (label15, 80, 32);

  label16 = gtk_label_new (_("telephone :"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 424, 440);
  gtk_widget_set_size_request (label16, 80, 32);

  ajLoginAdm = gtk_entry_new ();
  gtk_widget_show (ajLoginAdm);
  gtk_fixed_put (GTK_FIXED (fixed3), ajLoginAdm, 504, 376);
  gtk_widget_set_size_request (ajLoginAdm, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajLoginAdm), 8226);

  ajPassAdm = gtk_entry_new ();
  gtk_widget_show (ajPassAdm);
  gtk_fixed_put (GTK_FIXED (fixed3), ajPassAdm, 504, 408);
  gtk_widget_set_size_request (ajPassAdm, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (ajPassAdm), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajPassAdm), 8226);

  ajPhoneAdm = gtk_entry_new ();
  gtk_widget_show (ajPhoneAdm);
  gtk_fixed_put (GTK_FIXED (fixed3), ajPhoneAdm, 504, 440);
  gtk_widget_set_size_request (ajPhoneAdm, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajPhoneAdm), 8226);

  label7 = gtk_label_new (_("nom :"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed3), label7, 424, 128);
  gtk_widget_set_size_request (label7, 80, 32);

  ajSuppCompteAdm = gtk_button_new_with_mnemonic (_("Supprimer mon compte"));
  gtk_widget_show (ajSuppCompteAdm);
  gtk_fixed_put (GTK_FIXED (fixed3), ajSuppCompteAdm, 440, 504);
  gtk_widget_set_size_request (ajSuppCompteAdm, 192, 64);

  ajModifInfoAdm = gtk_button_new_with_mnemonic (_("Modifier mes infos"));
  gtk_widget_show (ajModifInfoAdm);
  gtk_fixed_put (GTK_FIXED (fixed3), ajModifInfoAdm, 688, 504);
  gtk_widget_set_size_request (ajModifInfoAdm, 152, 64);

  ajAjoutAdmn = gtk_button_new_with_mnemonic (_("Ajouter un Admin"));
  gtk_widget_show (ajAjoutAdmn);
  gtk_fixed_put (GTK_FIXED (fixed3), ajAjoutAdmn, 344, 592);
  gtk_widget_set_size_request (ajAjoutAdmn, 176, 64);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_compteAdmin, Gestion_compteAdmin, "Gestion_compteAdmin");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, label5, "label5");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, label6, "label6");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, ajNomAdm, "ajNomAdm");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, ajPrenomAdm, "ajPrenomAdm");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, label8, "label8");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, ajIdAdm, "ajIdAdm");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, label9, "label9");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, ajRoleAdm, "ajRoleAdm");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, label10, "label10");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, ajCinAdm, "ajCinAdm");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, label11, "label11");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, ajMailAdm, "ajMailAdm");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, label12, "label12");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, ajAdressAdm, "ajAdressAdm");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, label13, "label13");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, label14, "label14");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, label15, "label15");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, label16, "label16");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, ajLoginAdm, "ajLoginAdm");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, ajPassAdm, "ajPassAdm");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, ajPhoneAdm, "ajPhoneAdm");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, label7, "label7");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, ajSuppCompteAdm, "ajSuppCompteAdm");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, ajModifInfoAdm, "ajModifInfoAdm");
  GLADE_HOOKUP_OBJECT (Gestion_compteAdmin, ajAjoutAdmn, "ajAjoutAdmn");

  return Gestion_compteAdmin;
}

GtkWidget*
create_Ajout_Employe (void)
{
  GtkWidget *Ajout_Employe;
  GtkWidget *fixed5;
  GtkWidget *ajNomEmp;
  GtkWidget *ajPrenomEmp;
  GtkWidget *ajIdEmp;
  GtkWidget *ajCinEmp;
  GtkWidget *ajMailEmp;
  GtkWidget *ajAdressEmp;
  GtkWidget *ajLoginEmp;
  GtkWidget *ajPassEmp;
  GtkWidget *ajPhoneEmp;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkWidget *label29;
  GtkWidget *ajAjoutEmp;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label118;
  GtkWidget *label34;
  GtkWidget *label31;
  GtkWidget *label40;
  GtkWidget *label32;
  GtkWidget *ajErrAjoutEmp;

  Ajout_Employe = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajout_Employe), _("Ajout Employ\303\251"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Ajout_Employe), fixed5);
  gtk_widget_set_size_request (fixed5, 552, 576);

  ajNomEmp = gtk_entry_new ();
  gtk_widget_show (ajNomEmp);
  gtk_fixed_put (GTK_FIXED (fixed5), ajNomEmp, 392, 192);
  gtk_widget_set_size_request (ajNomEmp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajNomEmp), 8226);

  ajPrenomEmp = gtk_entry_new ();
  gtk_widget_show (ajPrenomEmp);
  gtk_fixed_put (GTK_FIXED (fixed5), ajPrenomEmp, 392, 232);
  gtk_widget_set_size_request (ajPrenomEmp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajPrenomEmp), 8226);

  ajIdEmp = gtk_entry_new ();
  gtk_widget_show (ajIdEmp);
  gtk_fixed_put (GTK_FIXED (fixed5), ajIdEmp, 392, 152);
  gtk_widget_set_size_request (ajIdEmp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajIdEmp), 8226);

  ajCinEmp = gtk_entry_new ();
  gtk_widget_show (ajCinEmp);
  gtk_fixed_put (GTK_FIXED (fixed5), ajCinEmp, 392, 272);
  gtk_widget_set_size_request (ajCinEmp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajCinEmp), 8226);

  ajMailEmp = gtk_entry_new ();
  gtk_widget_show (ajMailEmp);
  gtk_fixed_put (GTK_FIXED (fixed5), ajMailEmp, 392, 312);
  gtk_widget_set_size_request (ajMailEmp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajMailEmp), 8226);

  ajAdressEmp = gtk_entry_new ();
  gtk_widget_show (ajAdressEmp);
  gtk_fixed_put (GTK_FIXED (fixed5), ajAdressEmp, 392, 344);
  gtk_widget_set_size_request (ajAdressEmp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajAdressEmp), 8226);

  ajLoginEmp = gtk_entry_new ();
  gtk_widget_show (ajLoginEmp);
  gtk_fixed_put (GTK_FIXED (fixed5), ajLoginEmp, 392, 376);
  gtk_widget_set_size_request (ajLoginEmp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajLoginEmp), 8226);

  ajPassEmp = gtk_entry_new ();
  gtk_widget_show (ajPassEmp);
  gtk_fixed_put (GTK_FIXED (fixed5), ajPassEmp, 392, 408);
  gtk_widget_set_size_request (ajPassEmp, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (ajPassEmp), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajPassEmp), 8226);

  ajPhoneEmp = gtk_entry_new ();
  gtk_widget_show (ajPhoneEmp);
  gtk_fixed_put (GTK_FIXED (fixed5), ajPhoneEmp, 392, 440);
  gtk_widget_set_size_request (ajPhoneEmp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajPhoneEmp), 8226);

  label35 = gtk_label_new (_("E-mail :"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed5), label35, 304, 312);
  gtk_widget_set_size_request (label35, 80, 32);

  label36 = gtk_label_new (_("adresse :"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed5), label36, 296, 344);
  gtk_widget_set_size_request (label36, 80, 32);

  label37 = gtk_label_new (_("login :"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed5), label37, 304, 376);
  gtk_widget_set_size_request (label37, 80, 32);

  label38 = gtk_label_new (_("password :"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed5), label38, 304, 408);
  gtk_widget_set_size_request (label38, 80, 32);

  label39 = gtk_label_new (_("telephone :"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed5), label39, 304, 440);
  gtk_widget_set_size_request (label39, 80, 32);

  label29 = gtk_label_new (_("Ajout Employ\303\251"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed5), label29, 344, 0);
  gtk_widget_set_size_request (label29, 232, 72);

  ajAjoutEmp = gtk_button_new ();
  gtk_widget_show (ajAjoutEmp);
  gtk_fixed_put (GTK_FIXED (fixed5), ajAjoutEmp, 376, 512);
  gtk_widget_set_size_request (ajAjoutEmp, 176, 64);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (ajAjoutEmp), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label118 = gtk_label_new_with_mnemonic (_("Ajouter un Employ\303\251"));
  gtk_widget_show (label118);
  gtk_box_pack_start (GTK_BOX (hbox8), label118, FALSE, FALSE, 0);

  label34 = gtk_label_new (_("cin :"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed5), label34, 304, 272);
  gtk_widget_set_size_request (label34, 80, 32);

  label31 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed5), label31, 304, 232);
  gtk_widget_set_size_request (label31, 80, 32);

  label40 = gtk_label_new (_("nom :"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed5), label40, 320, 192);
  gtk_widget_set_size_request (label40, 80, 32);

  label32 = gtk_label_new (_("identifiant :"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed5), label32, 304, 152);
  gtk_widget_set_size_request (label32, 80, 32);

  ajErrAjoutEmp = gtk_label_new ("");
  gtk_widget_show (ajErrAjoutEmp);
  gtk_fixed_put (GTK_FIXED (fixed5), ajErrAjoutEmp, 16, 80);
  gtk_widget_set_size_request (ajErrAjoutEmp, 864, 40);

  g_signal_connect ((gpointer) ajAjoutEmp, "clicked",
                    G_CALLBACK (on_ajAjoutEmp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajout_Employe, Ajout_Employe, "Ajout_Employe");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, ajNomEmp, "ajNomEmp");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, ajPrenomEmp, "ajPrenomEmp");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, ajIdEmp, "ajIdEmp");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, ajCinEmp, "ajCinEmp");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, ajMailEmp, "ajMailEmp");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, ajAdressEmp, "ajAdressEmp");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, ajLoginEmp, "ajLoginEmp");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, ajPassEmp, "ajPassEmp");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, ajPhoneEmp, "ajPhoneEmp");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, label35, "label35");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, label36, "label36");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, label37, "label37");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, label38, "label38");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, label39, "label39");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, label29, "label29");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, ajAjoutEmp, "ajAjoutEmp");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, image8, "image8");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, label118, "label118");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, label34, "label34");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, label31, "label31");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, label40, "label40");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, label32, "label32");
  GLADE_HOOKUP_OBJECT (Ajout_Employe, ajErrAjoutEmp, "ajErrAjoutEmp");

  return Ajout_Employe;
}

GtkWidget*
create_Modifier_Employe (void)
{
  GtkWidget *Modifier_Employe;
  GtkWidget *fixed6;
  GtkWidget *ajNomEmp1;
  GtkWidget *ajPrenomEmp1;
  GtkWidget *ajCinEmp1;
  GtkWidget *ajMailEmp1;
  GtkWidget *ajAdressEmp1;
  GtkWidget *ajLoginEmp1;
  GtkWidget *ajPassEmp1;
  GtkWidget *ajPhoneEmp1;
  GtkWidget *label51;
  GtkWidget *ajModifEmp;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkWidget *ajRoleEmp1;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *label47;
  GtkWidget *label48;
  GtkWidget *label49;
  GtkWidget *label50;

  Modifier_Employe = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Modifier_Employe), _("Modifier Employ\303\251"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (Modifier_Employe), fixed6);
  gtk_widget_set_size_request (fixed6, 568, 576);

  ajNomEmp1 = gtk_entry_new ();
  gtk_widget_show (ajNomEmp1);
  gtk_fixed_put (GTK_FIXED (fixed6), ajNomEmp1, 392, 112);
  gtk_widget_set_size_request (ajNomEmp1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajNomEmp1), 8226);

  ajPrenomEmp1 = gtk_entry_new ();
  gtk_widget_show (ajPrenomEmp1);
  gtk_fixed_put (GTK_FIXED (fixed6), ajPrenomEmp1, 392, 152);
  gtk_widget_set_size_request (ajPrenomEmp1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajPrenomEmp1), 8226);

  ajCinEmp1 = gtk_entry_new ();
  gtk_widget_show (ajCinEmp1);
  gtk_fixed_put (GTK_FIXED (fixed6), ajCinEmp1, 392, 248);
  gtk_widget_set_size_request (ajCinEmp1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajCinEmp1), 8226);

  ajMailEmp1 = gtk_entry_new ();
  gtk_widget_show (ajMailEmp1);
  gtk_fixed_put (GTK_FIXED (fixed6), ajMailEmp1, 392, 288);
  gtk_widget_set_size_request (ajMailEmp1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajMailEmp1), 8226);

  ajAdressEmp1 = gtk_entry_new ();
  gtk_widget_show (ajAdressEmp1);
  gtk_fixed_put (GTK_FIXED (fixed6), ajAdressEmp1, 392, 328);
  gtk_widget_set_size_request (ajAdressEmp1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajAdressEmp1), 8226);

  ajLoginEmp1 = gtk_entry_new ();
  gtk_widget_show (ajLoginEmp1);
  gtk_fixed_put (GTK_FIXED (fixed6), ajLoginEmp1, 392, 368);
  gtk_widget_set_size_request (ajLoginEmp1, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (ajLoginEmp1), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajLoginEmp1), 8226);

  ajPassEmp1 = gtk_entry_new ();
  gtk_widget_show (ajPassEmp1);
  gtk_fixed_put (GTK_FIXED (fixed6), ajPassEmp1, 392, 408);
  gtk_widget_set_size_request (ajPassEmp1, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (ajPassEmp1), FALSE);
  gtk_entry_set_visibility (GTK_ENTRY (ajPassEmp1), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajPassEmp1), 8226);

  ajPhoneEmp1 = gtk_entry_new ();
  gtk_widget_show (ajPhoneEmp1);
  gtk_fixed_put (GTK_FIXED (fixed6), ajPhoneEmp1, 392, 440);
  gtk_widget_set_size_request (ajPhoneEmp1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajPhoneEmp1), 8226);

  label51 = gtk_label_new (_("telephone :"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed6), label51, 304, 440);
  gtk_widget_set_size_request (label51, 80, 32);

  ajModifEmp = gtk_button_new_with_mnemonic (_("Modifier un Employ\303\251"));
  gtk_widget_show (ajModifEmp);
  gtk_fixed_put (GTK_FIXED (fixed6), ajModifEmp, 376, 512);
  gtk_widget_set_size_request (ajModifEmp, 176, 64);

  label41 = gtk_label_new (_("Modifier Employ\303\251"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed6), label41, 336, 16);
  gtk_widget_set_size_request (label41, 232, 56);

  label42 = gtk_label_new (_("nom :"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed6), label42, 320, 112);
  gtk_widget_set_size_request (label42, 80, 32);

  label43 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed6), label43, 312, 144);
  gtk_widget_set_size_request (label43, 80, 32);

  ajRoleEmp1 = gtk_combo_box_new_text ();
  gtk_widget_show (ajRoleEmp1);
  gtk_fixed_put (GTK_FIXED (fixed6), ajRoleEmp1, 392, 200);
  gtk_widget_set_size_request (ajRoleEmp1, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajRoleEmp1), _("Admin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajRoleEmp1), _("Employ\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajRoleEmp1), _("Client"));

  label45 = gtk_label_new (_("role :"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed6), label45, 312, 200);
  gtk_widget_set_size_request (label45, 80, 32);

  label46 = gtk_label_new (_("cin :"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed6), label46, 304, 248);
  gtk_widget_set_size_request (label46, 80, 32);

  label47 = gtk_label_new (_("E-mail :"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed6), label47, 304, 288);
  gtk_widget_set_size_request (label47, 80, 32);

  label48 = gtk_label_new (_("adresse :"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed6), label48, 304, 328);
  gtk_widget_set_size_request (label48, 80, 32);

  label49 = gtk_label_new (_("login :"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed6), label49, 304, 368);
  gtk_widget_set_size_request (label49, 80, 32);

  label50 = gtk_label_new (_("password :"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed6), label50, 304, 400);
  gtk_widget_set_size_request (label50, 80, 32);

  g_signal_connect ((gpointer) ajModifEmp, "clicked",
                    G_CALLBACK (on_ajModifEmp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modifier_Employe, Modifier_Employe, "Modifier_Employe");
  GLADE_HOOKUP_OBJECT (Modifier_Employe, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Modifier_Employe, ajNomEmp1, "ajNomEmp1");
  GLADE_HOOKUP_OBJECT (Modifier_Employe, ajPrenomEmp1, "ajPrenomEmp1");
  GLADE_HOOKUP_OBJECT (Modifier_Employe, ajCinEmp1, "ajCinEmp1");
  GLADE_HOOKUP_OBJECT (Modifier_Employe, ajMailEmp1, "ajMailEmp1");
  GLADE_HOOKUP_OBJECT (Modifier_Employe, ajAdressEmp1, "ajAdressEmp1");
  GLADE_HOOKUP_OBJECT (Modifier_Employe, ajLoginEmp1, "ajLoginEmp1");
  GLADE_HOOKUP_OBJECT (Modifier_Employe, ajPassEmp1, "ajPassEmp1");
  GLADE_HOOKUP_OBJECT (Modifier_Employe, ajPhoneEmp1, "ajPhoneEmp1");
  GLADE_HOOKUP_OBJECT (Modifier_Employe, label51, "label51");
  GLADE_HOOKUP_OBJECT (Modifier_Employe, ajModifEmp, "ajModifEmp");
  GLADE_HOOKUP_OBJECT (Modifier_Employe, label41, "label41");
  GLADE_HOOKUP_OBJECT (Modifier_Employe, label42, "label42");
  GLADE_HOOKUP_OBJECT (Modifier_Employe, label43, "label43");
  GLADE_HOOKUP_OBJECT (Modifier_Employe, ajRoleEmp1, "ajRoleEmp1");
  GLADE_HOOKUP_OBJECT (Modifier_Employe, label45, "label45");
  GLADE_HOOKUP_OBJECT (Modifier_Employe, label46, "label46");
  GLADE_HOOKUP_OBJECT (Modifier_Employe, label47, "label47");
  GLADE_HOOKUP_OBJECT (Modifier_Employe, label48, "label48");
  GLADE_HOOKUP_OBJECT (Modifier_Employe, label49, "label49");
  GLADE_HOOKUP_OBJECT (Modifier_Employe, label50, "label50");

  return Modifier_Employe;
}

GtkWidget*
create_Modifier_Client (void)
{
  GtkWidget *Modifier_Client;
  GtkWidget *fixed7;
  GtkWidget *ajNomCli;
  GtkWidget *ajPrenomCli;
  GtkWidget *ajIdCli;
  GtkWidget *AjClassCli;
  GtkWidget *ajCinCli;
  GtkWidget *ajMailCli;
  GtkWidget *ajAdressCli;
  GtkWidget *ajLoginCli;
  GtkWidget *ajPassCli;
  GtkWidget *ajPhoneCli;
  GtkWidget *label52;
  GtkWidget *label53;
  GtkWidget *label54;
  GtkWidget *label56;
  GtkWidget *label57;
  GtkWidget *label58;
  GtkWidget *label59;
  GtkWidget *label60;
  GtkWidget *label61;
  GtkWidget *label55;
  GtkWidget *label62;
  GtkWidget *ajModifCli;

  Modifier_Client = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Modifier_Client), _("Modifier un Client"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (Modifier_Client), fixed7);

  ajNomCli = gtk_entry_new ();
  gtk_widget_show (ajNomCli);
  gtk_fixed_put (GTK_FIXED (fixed7), ajNomCli, 392, 128);
  gtk_widget_set_size_request (ajNomCli, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajNomCli), 8226);

  ajPrenomCli = gtk_entry_new ();
  gtk_widget_show (ajPrenomCli);
  gtk_fixed_put (GTK_FIXED (fixed7), ajPrenomCli, 392, 168);
  gtk_widget_set_size_request (ajPrenomCli, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajPrenomCli), 8226);

  ajIdCli = gtk_entry_new ();
  gtk_widget_show (ajIdCli);
  gtk_fixed_put (GTK_FIXED (fixed7), ajIdCli, 392, 208);
  gtk_widget_set_size_request (ajIdCli, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (ajIdCli), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajIdCli), 8226);

  AjClassCli = gtk_entry_new ();
  gtk_widget_show (AjClassCli);
  gtk_fixed_put (GTK_FIXED (fixed7), AjClassCli, 392, 248);
  gtk_widget_set_size_request (AjClassCli, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (AjClassCli), 8226);

  ajCinCli = gtk_entry_new ();
  gtk_widget_show (ajCinCli);
  gtk_fixed_put (GTK_FIXED (fixed7), ajCinCli, 392, 280);
  gtk_widget_set_size_request (ajCinCli, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajCinCli), 8226);

  ajMailCli = gtk_entry_new ();
  gtk_widget_show (ajMailCli);
  gtk_fixed_put (GTK_FIXED (fixed7), ajMailCli, 392, 312);
  gtk_widget_set_size_request (ajMailCli, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajMailCli), 8226);

  ajAdressCli = gtk_entry_new ();
  gtk_widget_show (ajAdressCli);
  gtk_fixed_put (GTK_FIXED (fixed7), ajAdressCli, 392, 344);
  gtk_widget_set_size_request (ajAdressCli, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajAdressCli), 8226);

  ajLoginCli = gtk_entry_new ();
  gtk_widget_show (ajLoginCli);
  gtk_fixed_put (GTK_FIXED (fixed7), ajLoginCli, 392, 376);
  gtk_widget_set_size_request (ajLoginCli, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajLoginCli), 8226);

  ajPassCli = gtk_entry_new ();
  gtk_widget_show (ajPassCli);
  gtk_fixed_put (GTK_FIXED (fixed7), ajPassCli, 392, 408);
  gtk_widget_set_size_request (ajPassCli, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (ajPassCli), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajPassCli), 8226);

  ajPhoneCli = gtk_entry_new ();
  gtk_widget_show (ajPhoneCli);
  gtk_fixed_put (GTK_FIXED (fixed7), ajPhoneCli, 392, 440);
  gtk_widget_set_size_request (ajPhoneCli, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajPhoneCli), 8226);

  label52 = gtk_label_new (_("nom :"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed7), label52, 320, 120);
  gtk_widget_set_size_request (label52, 80, 32);

  label53 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed7), label53, 304, 168);
  gtk_widget_set_size_request (label53, 80, 32);

  label54 = gtk_label_new (_("identifiant :"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed7), label54, 304, 208);
  gtk_widget_set_size_request (label54, 80, 32);

  label56 = gtk_label_new (_("cin :"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed7), label56, 304, 280);
  gtk_widget_set_size_request (label56, 80, 32);

  label57 = gtk_label_new (_("E-mail :"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed7), label57, 304, 312);
  gtk_widget_set_size_request (label57, 80, 32);

  label58 = gtk_label_new (_("adresse :"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed7), label58, 296, 344);
  gtk_widget_set_size_request (label58, 80, 32);

  label59 = gtk_label_new (_("login :"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed7), label59, 304, 376);
  gtk_widget_set_size_request (label59, 80, 32);

  label60 = gtk_label_new (_("password :"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed7), label60, 304, 408);
  gtk_widget_set_size_request (label60, 80, 32);

  label61 = gtk_label_new (_("telephone :"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed7), label61, 304, 440);
  gtk_widget_set_size_request (label61, 80, 32);

  label55 = gtk_label_new (_("Class :"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed7), label55, 304, 248);
  gtk_widget_set_size_request (label55, 80, 32);

  label62 = gtk_label_new (_("Modifier un Client"));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed7), label62, 336, 16);
  gtk_widget_set_size_request (label62, 232, 72);

  ajModifCli = gtk_button_new_with_mnemonic (_("Modifier un Client"));
  gtk_widget_show (ajModifCli);
  gtk_fixed_put (GTK_FIXED (fixed7), ajModifCli, 376, 512);
  gtk_widget_set_size_request (ajModifCli, 176, 64);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modifier_Client, Modifier_Client, "Modifier_Client");
  GLADE_HOOKUP_OBJECT (Modifier_Client, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (Modifier_Client, ajNomCli, "ajNomCli");
  GLADE_HOOKUP_OBJECT (Modifier_Client, ajPrenomCli, "ajPrenomCli");
  GLADE_HOOKUP_OBJECT (Modifier_Client, ajIdCli, "ajIdCli");
  GLADE_HOOKUP_OBJECT (Modifier_Client, AjClassCli, "AjClassCli");
  GLADE_HOOKUP_OBJECT (Modifier_Client, ajCinCli, "ajCinCli");
  GLADE_HOOKUP_OBJECT (Modifier_Client, ajMailCli, "ajMailCli");
  GLADE_HOOKUP_OBJECT (Modifier_Client, ajAdressCli, "ajAdressCli");
  GLADE_HOOKUP_OBJECT (Modifier_Client, ajLoginCli, "ajLoginCli");
  GLADE_HOOKUP_OBJECT (Modifier_Client, ajPassCli, "ajPassCli");
  GLADE_HOOKUP_OBJECT (Modifier_Client, ajPhoneCli, "ajPhoneCli");
  GLADE_HOOKUP_OBJECT (Modifier_Client, label52, "label52");
  GLADE_HOOKUP_OBJECT (Modifier_Client, label53, "label53");
  GLADE_HOOKUP_OBJECT (Modifier_Client, label54, "label54");
  GLADE_HOOKUP_OBJECT (Modifier_Client, label56, "label56");
  GLADE_HOOKUP_OBJECT (Modifier_Client, label57, "label57");
  GLADE_HOOKUP_OBJECT (Modifier_Client, label58, "label58");
  GLADE_HOOKUP_OBJECT (Modifier_Client, label59, "label59");
  GLADE_HOOKUP_OBJECT (Modifier_Client, label60, "label60");
  GLADE_HOOKUP_OBJECT (Modifier_Client, label61, "label61");
  GLADE_HOOKUP_OBJECT (Modifier_Client, label55, "label55");
  GLADE_HOOKUP_OBJECT (Modifier_Client, label62, "label62");
  GLADE_HOOKUP_OBJECT (Modifier_Client, ajModifCli, "ajModifCli");

  return Modifier_Client;
}

GtkWidget*
create_GestionClients (void)
{
  GtkWidget *GestionClients;
  GtkWidget *fixed8;
  GtkWidget *table2;
  GtkWidget *label64;
  GtkWidget *label65;
  GtkWidget *label66;
  GtkWidget *label67;
  GtkWidget *label68;
  GtkWidget *label69;
  GtkWidget *label70;
  GtkWidget *label71;
  GtkWidget *label72;
  GtkWidget *label73;
  GtkWidget *radiobutton5;
  GSList *radiobutton5_group = NULL;
  GtkWidget *radiobutton6;
  GSList *radiobutton6_group = NULL;
  GtkWidget *radiobutton7;
  GSList *radiobutton7_group = NULL;
  GtkWidget *radiobutton8;
  GSList *radiobutton8_group = NULL;
  GtkWidget *label63;
  GtkWidget *ajModifierCli;
  GtkWidget *ajSupprimerCli;
  GtkWidget *ajAjouterCli;

  GestionClients = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GestionClients), _("Gestion des Clients"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (GestionClients), fixed8);

  table2 = gtk_table_new (5, 11, FALSE);
  gtk_widget_show (table2);
  gtk_fixed_put (GTK_FIXED (fixed8), table2, 170, 138);
  gtk_widget_set_size_request (table2, 160, 80);

  label64 = gtk_label_new (_("Nom"));
  gtk_widget_show (label64);
  gtk_table_attach (GTK_TABLE (table2), label64, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label64, 41, -1);
  gtk_misc_set_alignment (GTK_MISC (label64), 0, 0.5);

  label65 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label65);
  gtk_table_attach (GTK_TABLE (table2), label65, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label65, 57, -1);
  gtk_misc_set_alignment (GTK_MISC (label65), 0, 0.5);

  label66 = gtk_label_new (_("identifiant"));
  gtk_widget_show (label66);
  gtk_table_attach (GTK_TABLE (table2), label66, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label66, 73, -1);
  gtk_misc_set_alignment (GTK_MISC (label66), 0, 0.5);

  label67 = gtk_label_new (_("Role"));
  gtk_widget_show (label67);
  gtk_table_attach (GTK_TABLE (table2), label67, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label67, 36, -1);
  gtk_misc_set_alignment (GTK_MISC (label67), 0, 0.5);

  label68 = gtk_label_new (_("E-mail"));
  gtk_widget_show (label68);
  gtk_table_attach (GTK_TABLE (table2), label68, 5, 6, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label68, 47, -1);
  gtk_misc_set_alignment (GTK_MISC (label68), 0, 0.5);

  label69 = gtk_label_new (_("Adresse"));
  gtk_widget_show (label69);
  gtk_table_attach (GTK_TABLE (table2), label69, 6, 7, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label69, 60, -1);
  gtk_misc_set_alignment (GTK_MISC (label69), 0, 0.5);

  label70 = gtk_label_new (_("Cin"));
  gtk_widget_show (label70);
  gtk_table_attach (GTK_TABLE (table2), label70, 7, 8, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label70, 26, -1);
  gtk_misc_set_alignment (GTK_MISC (label70), 0, 0.5);

  label71 = gtk_label_new (_("T\303\251l\303\251phone"));
  gtk_widget_show (label71);
  gtk_table_attach (GTK_TABLE (table2), label71, 8, 9, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label71, 73, -1);
  gtk_misc_set_alignment (GTK_MISC (label71), 0, 0.5);

  label72 = gtk_label_new (_("Login"));
  gtk_widget_show (label72);
  gtk_table_attach (GTK_TABLE (table2), label72, 9, 10, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label72, 42, -1);
  gtk_misc_set_alignment (GTK_MISC (label72), 0, 0.5);

  label73 = gtk_label_new (_("Password"));
  gtk_widget_show (label73);
  gtk_table_attach (GTK_TABLE (table2), label73, 10, 11, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label73, 70, -1);
  gtk_misc_set_alignment (GTK_MISC (label73), 0, 0.5);

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, "");
  gtk_widget_show (radiobutton5);
  gtk_table_attach (GTK_TABLE (table2), radiobutton5, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton5_group);
  radiobutton5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, "");
  gtk_widget_show (radiobutton6);
  gtk_table_attach (GTK_TABLE (table2), radiobutton6, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton6_group);
  radiobutton6_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, "");
  gtk_widget_show (radiobutton7);
  gtk_table_attach (GTK_TABLE (table2), radiobutton7, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  radiobutton8 = gtk_radio_button_new_with_mnemonic (NULL, "");
  gtk_widget_show (radiobutton8);
  gtk_table_attach (GTK_TABLE (table2), radiobutton8, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton8), radiobutton8_group);
  radiobutton8_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton8));

  label63 = gtk_label_new (_("Gestion des Clients"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed8), label63, 328, 24);
  gtk_widget_set_size_request (label63, 192, 48);

  ajModifierCli = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (ajModifierCli);
  gtk_fixed_put (GTK_FIXED (fixed8), ajModifierCli, 264, 320);
  gtk_widget_set_size_request (ajModifierCli, 138, 48);

  ajSupprimerCli = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (ajSupprimerCli);
  gtk_fixed_put (GTK_FIXED (fixed8), ajSupprimerCli, 456, 320);
  gtk_widget_set_size_request (ajSupprimerCli, 138, 48);

  ajAjouterCli = gtk_button_new_with_mnemonic (_("Ajouter un Client"));
  gtk_widget_show (ajAjouterCli);
  gtk_fixed_put (GTK_FIXED (fixed8), ajAjouterCli, 336, 488);
  gtk_widget_set_size_request (ajAjouterCli, 160, 56);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GestionClients, GestionClients, "GestionClients");
  GLADE_HOOKUP_OBJECT (GestionClients, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (GestionClients, table2, "table2");
  GLADE_HOOKUP_OBJECT (GestionClients, label64, "label64");
  GLADE_HOOKUP_OBJECT (GestionClients, label65, "label65");
  GLADE_HOOKUP_OBJECT (GestionClients, label66, "label66");
  GLADE_HOOKUP_OBJECT (GestionClients, label67, "label67");
  GLADE_HOOKUP_OBJECT (GestionClients, label68, "label68");
  GLADE_HOOKUP_OBJECT (GestionClients, label69, "label69");
  GLADE_HOOKUP_OBJECT (GestionClients, label70, "label70");
  GLADE_HOOKUP_OBJECT (GestionClients, label71, "label71");
  GLADE_HOOKUP_OBJECT (GestionClients, label72, "label72");
  GLADE_HOOKUP_OBJECT (GestionClients, label73, "label73");
  GLADE_HOOKUP_OBJECT (GestionClients, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (GestionClients, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (GestionClients, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (GestionClients, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (GestionClients, label63, "label63");
  GLADE_HOOKUP_OBJECT (GestionClients, ajModifierCli, "ajModifierCli");
  GLADE_HOOKUP_OBJECT (GestionClients, ajSupprimerCli, "ajSupprimerCli");
  GLADE_HOOKUP_OBJECT (GestionClients, ajAjouterCli, "ajAjouterCli");

  return GestionClients;
}

GtkWidget*
create_Recherche (void)
{
  GtkWidget *Recherche;
  GtkWidget *fixed9;
  GtkWidget *label75;
  GtkWidget *ajIdRech;
  GtkWidget *ajResRech;
  GtkWidget *label76;
  GtkWidget *ajRoleRech;
  GtkWidget *label74;
  GtkWidget *ajRechercher;

  Recherche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Recherche), _("Recherche"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (Recherche), fixed9);

  label75 = gtk_label_new (_("choisir le role :"));
  gtk_widget_show (label75);
  gtk_fixed_put (GTK_FIXED (fixed9), label75, 224, 88);
  gtk_widget_set_size_request (label75, 112, 40);

  ajIdRech = gtk_entry_new ();
  gtk_widget_show (ajIdRech);
  gtk_fixed_put (GTK_FIXED (fixed9), ajIdRech, 344, 160);
  gtk_widget_set_size_request (ajIdRech, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajIdRech), 8226);

  ajResRech = gtk_text_view_new ();
  gtk_widget_show (ajResRech);
  gtk_fixed_put (GTK_FIXED (fixed9), ajResRech, 176, 272);
  gtk_widget_set_size_request (ajResRech, 488, 400);

  label76 = gtk_label_new (_("identifiant :"));
  gtk_widget_show (label76);
  gtk_fixed_put (GTK_FIXED (fixed9), label76, 232, 152);
  gtk_widget_set_size_request (label76, 88, 32);

  ajRoleRech = gtk_combo_box_entry_new_text ();
  gtk_widget_show (ajRoleRech);
  gtk_fixed_put (GTK_FIXED (fixed9), ajRoleRech, 344, 96);
  gtk_widget_set_size_request (ajRoleRech, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajRoleRech), _("\t\t--Role--"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajRoleRech), _("employ\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajRoleRech), _("client"));

  label74 = gtk_label_new (_("Recherche"));
  gtk_widget_show (label74);
  gtk_fixed_put (GTK_FIXED (fixed9), label74, 320, 24);
  gtk_widget_set_size_request (label74, 128, 40);

  ajRechercher = gtk_button_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (ajRechercher);
  gtk_fixed_put (GTK_FIXED (fixed9), ajRechercher, 312, 208);
  gtk_widget_set_size_request (ajRechercher, 128, 48);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Recherche, Recherche, "Recherche");
  GLADE_HOOKUP_OBJECT (Recherche, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (Recherche, label75, "label75");
  GLADE_HOOKUP_OBJECT (Recherche, ajIdRech, "ajIdRech");
  GLADE_HOOKUP_OBJECT (Recherche, ajResRech, "ajResRech");
  GLADE_HOOKUP_OBJECT (Recherche, label76, "label76");
  GLADE_HOOKUP_OBJECT (Recherche, ajRoleRech, "ajRoleRech");
  GLADE_HOOKUP_OBJECT (Recherche, label74, "label74");
  GLADE_HOOKUP_OBJECT (Recherche, ajRechercher, "ajRechercher");

  return Recherche;
}

GtkWidget*
create_Espace_Emp (void)
{
  GtkWidget *Espace_Emp;
  GtkWidget *fixed10;
  GtkWidget *label77;
  GtkWidget *ajGestionCli;
  GtkWidget *ajRecherche;
  GtkWidget *ajConsRec;
  GtkWidget *ajGestionFact;
  GtkWidget *ajGestionService;

  Espace_Emp = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Espace_Emp), _("Espace Employ\303\251"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (Espace_Emp), fixed10);

  label77 = gtk_label_new (_("Espace Employ\303\251"));
  gtk_widget_show (label77);
  gtk_fixed_put (GTK_FIXED (fixed10), label77, 336, 24);
  gtk_widget_set_size_request (label77, 184, 56);

  ajGestionCli = gtk_button_new_with_mnemonic (_("Gestion des clients"));
  gtk_widget_show (ajGestionCli);
  gtk_fixed_put (GTK_FIXED (fixed10), ajGestionCli, 328, 104);
  gtk_widget_set_size_request (ajGestionCli, 216, 64);

  ajRecherche = gtk_button_new_with_mnemonic (_("Recherche"));
  gtk_widget_show (ajRecherche);
  gtk_fixed_put (GTK_FIXED (fixed10), ajRecherche, 328, 200);
  gtk_widget_set_size_request (ajRecherche, 216, 64);

  ajConsRec = gtk_button_new_with_mnemonic (_("Consultation des r\303\251clamations"));
  gtk_widget_show (ajConsRec);
  gtk_fixed_put (GTK_FIXED (fixed10), ajConsRec, 320, 288);
  gtk_widget_set_size_request (ajConsRec, 232, 88);

  ajGestionFact = gtk_button_new_with_mnemonic (_("Gestion des factures"));
  gtk_widget_show (ajGestionFact);
  gtk_fixed_put (GTK_FIXED (fixed10), ajGestionFact, 352, 400);
  gtk_widget_set_size_request (ajGestionFact, 176, 56);

  ajGestionService = gtk_button_new_with_mnemonic (_("Gestion des services"));
  gtk_widget_show (ajGestionService);
  gtk_fixed_put (GTK_FIXED (fixed10), ajGestionService, 320, 480);
  gtk_widget_set_size_request (ajGestionService, 224, 64);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Espace_Emp, Espace_Emp, "Espace_Emp");
  GLADE_HOOKUP_OBJECT (Espace_Emp, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (Espace_Emp, label77, "label77");
  GLADE_HOOKUP_OBJECT (Espace_Emp, ajGestionCli, "ajGestionCli");
  GLADE_HOOKUP_OBJECT (Espace_Emp, ajRecherche, "ajRecherche");
  GLADE_HOOKUP_OBJECT (Espace_Emp, ajConsRec, "ajConsRec");
  GLADE_HOOKUP_OBJECT (Espace_Emp, ajGestionFact, "ajGestionFact");
  GLADE_HOOKUP_OBJECT (Espace_Emp, ajGestionService, "ajGestionService");

  return Espace_Emp;
}

GtkWidget*
create_Ajout_client (void)
{
  GtkWidget *Ajout_client;
  GtkWidget *fixed11;
  GtkWidget *ajNomCli1;
  GtkWidget *ajPrenomCli1;
  GtkWidget *ajIdCli1;
  GtkWidget *AjClassCli1;
  GtkWidget *ajCinCli1;
  GtkWidget *ajMailCli1;
  GtkWidget *ajAdressCli1;
  GtkWidget *ajLoginCli1;
  GtkWidget *ajPassCli1;
  GtkWidget *ajPhoneCli1;
  GtkWidget *label89;
  GtkWidget *label90;
  GtkWidget *label91;
  GtkWidget *label93;
  GtkWidget *label94;
  GtkWidget *label95;
  GtkWidget *label96;
  GtkWidget *label97;
  GtkWidget *label98;
  GtkWidget *label88;
  GtkWidget *label92;
  GtkWidget *ajAjoutCli;

  Ajout_client = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajout_client), _("Ajout du client"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (Ajout_client), fixed11);

  ajNomCli1 = gtk_entry_new ();
  gtk_widget_show (ajNomCli1);
  gtk_fixed_put (GTK_FIXED (fixed11), ajNomCli1, 392, 128);
  gtk_widget_set_size_request (ajNomCli1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajNomCli1), 8226);

  ajPrenomCli1 = gtk_entry_new ();
  gtk_widget_show (ajPrenomCli1);
  gtk_fixed_put (GTK_FIXED (fixed11), ajPrenomCli1, 392, 168);
  gtk_widget_set_size_request (ajPrenomCli1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajPrenomCli1), 8226);

  ajIdCli1 = gtk_entry_new ();
  gtk_widget_show (ajIdCli1);
  gtk_fixed_put (GTK_FIXED (fixed11), ajIdCli1, 392, 208);
  gtk_widget_set_size_request (ajIdCli1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajIdCli1), 8226);

  AjClassCli1 = gtk_entry_new ();
  gtk_widget_show (AjClassCli1);
  gtk_fixed_put (GTK_FIXED (fixed11), AjClassCli1, 392, 248);
  gtk_widget_set_size_request (AjClassCli1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (AjClassCli1), 8226);

  ajCinCli1 = gtk_entry_new ();
  gtk_widget_show (ajCinCli1);
  gtk_fixed_put (GTK_FIXED (fixed11), ajCinCli1, 392, 280);
  gtk_widget_set_size_request (ajCinCli1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajCinCli1), 8226);

  ajMailCli1 = gtk_entry_new ();
  gtk_widget_show (ajMailCli1);
  gtk_fixed_put (GTK_FIXED (fixed11), ajMailCli1, 392, 312);
  gtk_widget_set_size_request (ajMailCli1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajMailCli1), 8226);

  ajAdressCli1 = gtk_entry_new ();
  gtk_widget_show (ajAdressCli1);
  gtk_fixed_put (GTK_FIXED (fixed11), ajAdressCli1, 392, 344);
  gtk_widget_set_size_request (ajAdressCli1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajAdressCli1), 8226);

  ajLoginCli1 = gtk_entry_new ();
  gtk_widget_show (ajLoginCli1);
  gtk_fixed_put (GTK_FIXED (fixed11), ajLoginCli1, 392, 376);
  gtk_widget_set_size_request (ajLoginCli1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajLoginCli1), 8226);

  ajPassCli1 = gtk_entry_new ();
  gtk_widget_show (ajPassCli1);
  gtk_fixed_put (GTK_FIXED (fixed11), ajPassCli1, 392, 408);
  gtk_widget_set_size_request (ajPassCli1, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (ajPassCli1), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajPassCli1), 8226);

  ajPhoneCli1 = gtk_entry_new ();
  gtk_widget_show (ajPhoneCli1);
  gtk_fixed_put (GTK_FIXED (fixed11), ajPhoneCli1, 392, 440);
  gtk_widget_set_size_request (ajPhoneCli1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajPhoneCli1), 8226);

  label89 = gtk_label_new (_("nom :"));
  gtk_widget_show (label89);
  gtk_fixed_put (GTK_FIXED (fixed11), label89, 320, 120);
  gtk_widget_set_size_request (label89, 80, 32);

  label90 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed11), label90, 304, 168);
  gtk_widget_set_size_request (label90, 80, 32);

  label91 = gtk_label_new (_("identifiant :"));
  gtk_widget_show (label91);
  gtk_fixed_put (GTK_FIXED (fixed11), label91, 304, 208);
  gtk_widget_set_size_request (label91, 80, 32);

  label93 = gtk_label_new (_("cin :"));
  gtk_widget_show (label93);
  gtk_fixed_put (GTK_FIXED (fixed11), label93, 304, 280);
  gtk_widget_set_size_request (label93, 80, 32);

  label94 = gtk_label_new (_("E-mail :"));
  gtk_widget_show (label94);
  gtk_fixed_put (GTK_FIXED (fixed11), label94, 304, 312);
  gtk_widget_set_size_request (label94, 80, 32);

  label95 = gtk_label_new (_("adresse :"));
  gtk_widget_show (label95);
  gtk_fixed_put (GTK_FIXED (fixed11), label95, 296, 344);
  gtk_widget_set_size_request (label95, 80, 32);

  label96 = gtk_label_new (_("login :"));
  gtk_widget_show (label96);
  gtk_fixed_put (GTK_FIXED (fixed11), label96, 304, 376);
  gtk_widget_set_size_request (label96, 80, 32);

  label97 = gtk_label_new (_("password :"));
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed11), label97, 304, 408);
  gtk_widget_set_size_request (label97, 80, 32);

  label98 = gtk_label_new (_("telephone :"));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed11), label98, 304, 440);
  gtk_widget_set_size_request (label98, 80, 32);

  label88 = gtk_label_new (_("Ajout Client"));
  gtk_widget_show (label88);
  gtk_fixed_put (GTK_FIXED (fixed11), label88, 336, 24);
  gtk_widget_set_size_request (label88, 232, 72);

  label92 = gtk_label_new (_("class :"));
  gtk_widget_show (label92);
  gtk_fixed_put (GTK_FIXED (fixed11), label92, 304, 248);
  gtk_widget_set_size_request (label92, 80, 32);

  ajAjoutCli = gtk_button_new_with_mnemonic (_("Ajouter un Client"));
  gtk_widget_show (ajAjoutCli);
  gtk_fixed_put (GTK_FIXED (fixed11), ajAjoutCli, 376, 512);
  gtk_widget_set_size_request (ajAjoutCli, 176, 64);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajout_client, Ajout_client, "Ajout_client");
  GLADE_HOOKUP_OBJECT (Ajout_client, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (Ajout_client, ajNomCli1, "ajNomCli1");
  GLADE_HOOKUP_OBJECT (Ajout_client, ajPrenomCli1, "ajPrenomCli1");
  GLADE_HOOKUP_OBJECT (Ajout_client, ajIdCli1, "ajIdCli1");
  GLADE_HOOKUP_OBJECT (Ajout_client, AjClassCli1, "AjClassCli1");
  GLADE_HOOKUP_OBJECT (Ajout_client, ajCinCli1, "ajCinCli1");
  GLADE_HOOKUP_OBJECT (Ajout_client, ajMailCli1, "ajMailCli1");
  GLADE_HOOKUP_OBJECT (Ajout_client, ajAdressCli1, "ajAdressCli1");
  GLADE_HOOKUP_OBJECT (Ajout_client, ajLoginCli1, "ajLoginCli1");
  GLADE_HOOKUP_OBJECT (Ajout_client, ajPassCli1, "ajPassCli1");
  GLADE_HOOKUP_OBJECT (Ajout_client, ajPhoneCli1, "ajPhoneCli1");
  GLADE_HOOKUP_OBJECT (Ajout_client, label89, "label89");
  GLADE_HOOKUP_OBJECT (Ajout_client, label90, "label90");
  GLADE_HOOKUP_OBJECT (Ajout_client, label91, "label91");
  GLADE_HOOKUP_OBJECT (Ajout_client, label93, "label93");
  GLADE_HOOKUP_OBJECT (Ajout_client, label94, "label94");
  GLADE_HOOKUP_OBJECT (Ajout_client, label95, "label95");
  GLADE_HOOKUP_OBJECT (Ajout_client, label96, "label96");
  GLADE_HOOKUP_OBJECT (Ajout_client, label97, "label97");
  GLADE_HOOKUP_OBJECT (Ajout_client, label98, "label98");
  GLADE_HOOKUP_OBJECT (Ajout_client, label88, "label88");
  GLADE_HOOKUP_OBJECT (Ajout_client, label92, "label92");
  GLADE_HOOKUP_OBJECT (Ajout_client, ajAjoutCli, "ajAjoutCli");

  return Ajout_client;
}

GtkWidget*
create_Ajout_Admin (void)
{
  GtkWidget *Ajout_Admin;
  GtkWidget *fixed12;
  GtkWidget *ajNomAdm1;
  GtkWidget *ajPrenomAdm1;
  GtkWidget *ajIdAdm1;
  GtkWidget *ajRoleAdm1;
  GtkWidget *ajCinAdm1;
  GtkWidget *ajMailAdm1;
  GtkWidget *ajAdressAdm1;
  GtkWidget *ajLoginAdm1;
  GtkWidget *ajPassAdm1;
  GtkWidget *ajPhoneAdm1;
  GtkWidget *label101;
  GtkWidget *label102;
  GtkWidget *label103;
  GtkWidget *label104;
  GtkWidget *label105;
  GtkWidget *label106;
  GtkWidget *label107;
  GtkWidget *label108;
  GtkWidget *label109;
  GtkWidget *label100;
  GtkWidget *label99;
  GtkWidget *ajAjoutAdm1;

  Ajout_Admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Ajout_Admin, 550, 576);
  gtk_window_set_title (GTK_WINDOW (Ajout_Admin), _("Ajout Admin"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (Ajout_Admin), fixed12);
  gtk_widget_set_size_request (fixed12, 552, 576);

  ajNomAdm1 = gtk_entry_new ();
  gtk_widget_show (ajNomAdm1);
  gtk_fixed_put (GTK_FIXED (fixed12), ajNomAdm1, 392, 128);
  gtk_widget_set_size_request (ajNomAdm1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajNomAdm1), 8226);

  ajPrenomAdm1 = gtk_entry_new ();
  gtk_widget_show (ajPrenomAdm1);
  gtk_fixed_put (GTK_FIXED (fixed12), ajPrenomAdm1, 392, 168);
  gtk_widget_set_size_request (ajPrenomAdm1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajPrenomAdm1), 8226);

  ajIdAdm1 = gtk_entry_new ();
  gtk_widget_show (ajIdAdm1);
  gtk_fixed_put (GTK_FIXED (fixed12), ajIdAdm1, 392, 208);
  gtk_widget_set_size_request (ajIdAdm1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajIdAdm1), 8226);

  ajRoleAdm1 = gtk_entry_new ();
  gtk_widget_show (ajRoleAdm1);
  gtk_fixed_put (GTK_FIXED (fixed12), ajRoleAdm1, 392, 248);
  gtk_widget_set_size_request (ajRoleAdm1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajRoleAdm1), 8226);

  ajCinAdm1 = gtk_entry_new ();
  gtk_widget_show (ajCinAdm1);
  gtk_fixed_put (GTK_FIXED (fixed12), ajCinAdm1, 392, 280);
  gtk_widget_set_size_request (ajCinAdm1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajCinAdm1), 8226);

  ajMailAdm1 = gtk_entry_new ();
  gtk_widget_show (ajMailAdm1);
  gtk_fixed_put (GTK_FIXED (fixed12), ajMailAdm1, 392, 312);
  gtk_widget_set_size_request (ajMailAdm1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajMailAdm1), 8226);

  ajAdressAdm1 = gtk_entry_new ();
  gtk_widget_show (ajAdressAdm1);
  gtk_fixed_put (GTK_FIXED (fixed12), ajAdressAdm1, 392, 344);
  gtk_widget_set_size_request (ajAdressAdm1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajAdressAdm1), 8226);

  ajLoginAdm1 = gtk_entry_new ();
  gtk_widget_show (ajLoginAdm1);
  gtk_fixed_put (GTK_FIXED (fixed12), ajLoginAdm1, 392, 376);
  gtk_widget_set_size_request (ajLoginAdm1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajLoginAdm1), 8226);

  ajPassAdm1 = gtk_entry_new ();
  gtk_widget_show (ajPassAdm1);
  gtk_fixed_put (GTK_FIXED (fixed12), ajPassAdm1, 392, 408);
  gtk_widget_set_size_request (ajPassAdm1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajPassAdm1), 8226);

  ajPhoneAdm1 = gtk_entry_new ();
  gtk_widget_show (ajPhoneAdm1);
  gtk_fixed_put (GTK_FIXED (fixed12), ajPhoneAdm1, 392, 440);
  gtk_widget_set_size_request (ajPhoneAdm1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajPhoneAdm1), 8226);

  label101 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label101);
  gtk_fixed_put (GTK_FIXED (fixed12), label101, 304, 168);
  gtk_widget_set_size_request (label101, 80, 32);

  label102 = gtk_label_new (_("identifiant :"));
  gtk_widget_show (label102);
  gtk_fixed_put (GTK_FIXED (fixed12), label102, 304, 208);
  gtk_widget_set_size_request (label102, 80, 32);

  label103 = gtk_label_new (_("role :"));
  gtk_widget_show (label103);
  gtk_fixed_put (GTK_FIXED (fixed12), label103, 304, 248);
  gtk_widget_set_size_request (label103, 80, 32);

  label104 = gtk_label_new (_("cin :"));
  gtk_widget_show (label104);
  gtk_fixed_put (GTK_FIXED (fixed12), label104, 304, 280);
  gtk_widget_set_size_request (label104, 80, 32);

  label105 = gtk_label_new (_("E-mail :"));
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed12), label105, 304, 312);
  gtk_widget_set_size_request (label105, 80, 32);

  label106 = gtk_label_new (_("adresse :"));
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed12), label106, 296, 344);
  gtk_widget_set_size_request (label106, 80, 32);

  label107 = gtk_label_new (_("login :"));
  gtk_widget_show (label107);
  gtk_fixed_put (GTK_FIXED (fixed12), label107, 304, 376);
  gtk_widget_set_size_request (label107, 80, 32);

  label108 = gtk_label_new (_("password :"));
  gtk_widget_show (label108);
  gtk_fixed_put (GTK_FIXED (fixed12), label108, 304, 408);
  gtk_widget_set_size_request (label108, 80, 32);

  label109 = gtk_label_new (_("telephone :"));
  gtk_widget_show (label109);
  gtk_fixed_put (GTK_FIXED (fixed12), label109, 304, 440);
  gtk_widget_set_size_request (label109, 80, 32);

  label100 = gtk_label_new (_("nom :"));
  gtk_widget_show (label100);
  gtk_fixed_put (GTK_FIXED (fixed12), label100, 320, 120);
  gtk_widget_set_size_request (label100, 80, 32);

  label99 = gtk_label_new (_("Ajout Admin"));
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed12), label99, 320, 0);
  gtk_widget_set_size_request (label99, 232, 72);

  ajAjoutAdm1 = gtk_button_new_with_mnemonic (_("Ajouter un Employ\303\251"));
  gtk_widget_show (ajAjoutAdm1);
  gtk_fixed_put (GTK_FIXED (fixed12), ajAjoutAdm1, 376, 512);
  gtk_widget_set_size_request (ajAjoutAdm1, 176, 64);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajout_Admin, Ajout_Admin, "Ajout_Admin");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, ajNomAdm1, "ajNomAdm1");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, ajPrenomAdm1, "ajPrenomAdm1");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, ajIdAdm1, "ajIdAdm1");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, ajRoleAdm1, "ajRoleAdm1");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, ajCinAdm1, "ajCinAdm1");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, ajMailAdm1, "ajMailAdm1");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, ajAdressAdm1, "ajAdressAdm1");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, ajLoginAdm1, "ajLoginAdm1");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, ajPassAdm1, "ajPassAdm1");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, ajPhoneAdm1, "ajPhoneAdm1");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, label101, "label101");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, label102, "label102");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, label103, "label103");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, label104, "label104");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, label105, "label105");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, label106, "label106");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, label107, "label107");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, label108, "label108");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, label109, "label109");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, label100, "label100");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, label99, "label99");
  GLADE_HOOKUP_OBJECT (Ajout_Admin, ajAjoutAdm1, "ajAjoutAdm1");

  return Ajout_Admin;
}

GtkWidget*
create_EspaceCli (void)
{
  GtkWidget *EspaceCli;
  GtkWidget *fixed13;
  GtkWidget *label119;

  EspaceCli = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (EspaceCli), _("window1"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (EspaceCli), fixed13);

  label119 = gtk_label_new (_("Espace client"));
  gtk_widget_show (label119);
  gtk_fixed_put (GTK_FIXED (fixed13), label119, 320, 32);
  gtk_widget_set_size_request (label119, 144, 40);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (EspaceCli, EspaceCli, "EspaceCli");
  GLADE_HOOKUP_OBJECT (EspaceCli, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (EspaceCli, label119, "label119");

  return EspaceCli;
}

GtkWidget*
create_GestionEmp (void)
{
  GtkWidget *GestionEmp;
  GtkWidget *fixed14;
  GtkWidget *ajAffichageEmp;
  GtkWidget *ajGoToAjoutEmploy;
  GtkWidget *label120;
  GtkWidget *label121;
  GtkWidget *ajTSMEmp;
  GtkWidget *ajModifEmploy;
  GtkWidget *ajErrTSMEMP;
  GtkWidget *mmmm;
  GtkWidget *ajSuppEmploy;

  GestionEmp = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GestionEmp), _("Gestion des Employ\303\251s"));
  gtk_window_set_default_size (GTK_WINDOW (GestionEmp), 800, 550);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (GestionEmp), fixed14);

  ajAffichageEmp = gtk_tree_view_new ();
  gtk_widget_show (ajAffichageEmp);
  gtk_fixed_put (GTK_FIXED (fixed14), ajAffichageEmp, 24, 80);
  gtk_widget_set_size_request (ajAffichageEmp, 752, 224);

  ajGoToAjoutEmploy = gtk_button_new_with_mnemonic (_("Ajouter un Employ\303\251"));
  gtk_widget_show (ajGoToAjoutEmploy);
  gtk_fixed_put (GTK_FIXED (fixed14), ajGoToAjoutEmploy, 336, 488);
  gtk_widget_set_size_request (ajGoToAjoutEmploy, 160, 56);

  label120 = gtk_label_new (_("Gestion des Employ\303\251s"));
  gtk_widget_show (label120);
  gtk_fixed_put (GTK_FIXED (fixed14), label120, 328, 8);
  gtk_widget_set_size_request (label120, 192, 48);

  label121 = gtk_label_new (_("choisir l'identifiant du client :"));
  gtk_widget_show (label121);
  gtk_fixed_put (GTK_FIXED (fixed14), label121, 208, 352);
  gtk_widget_set_size_request (label121, 200, 48);

  ajTSMEmp = gtk_entry_new ();
  gtk_widget_show (ajTSMEmp);
  gtk_fixed_put (GTK_FIXED (fixed14), ajTSMEmp, 416, 368);
  gtk_widget_set_size_request (ajTSMEmp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajTSMEmp), 8226);

  ajModifEmploy = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (ajModifEmploy);
  gtk_fixed_put (GTK_FIXED (fixed14), ajModifEmploy, 200, 416);
  gtk_widget_set_size_request (ajModifEmploy, 138, 48);

  ajErrTSMEMP = gtk_label_new ("");
  gtk_widget_show (ajErrTSMEMP);
  gtk_fixed_put (GTK_FIXED (fixed14), ajErrTSMEMP, 304, 328);
  gtk_widget_set_size_request (ajErrTSMEMP, 240, 32);

  mmmm = gtk_label_new ("");
  gtk_widget_show (mmmm);
  gtk_fixed_put (GTK_FIXED (fixed14), mmmm, 72, 392);
  gtk_widget_set_size_request (mmmm, 88, 40);

  ajSuppEmploy = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (ajSuppEmploy);
  gtk_fixed_put (GTK_FIXED (fixed14), ajSuppEmploy, 496, 416);
  gtk_widget_set_size_request (ajSuppEmploy, 138, 48);

  g_signal_connect ((gpointer) ajGoToAjoutEmploy, "clicked",
                    G_CALLBACK (on_ajGoToAjoutEmploy_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajModifEmploy, "clicked",
                    G_CALLBACK (on_ajModifEmploy_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajSuppEmploy, "clicked",
                    G_CALLBACK (on_ajSuppEmploy_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GestionEmp, GestionEmp, "GestionEmp");
  GLADE_HOOKUP_OBJECT (GestionEmp, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (GestionEmp, ajAffichageEmp, "ajAffichageEmp");
  GLADE_HOOKUP_OBJECT (GestionEmp, ajGoToAjoutEmploy, "ajGoToAjoutEmploy");
  GLADE_HOOKUP_OBJECT (GestionEmp, label120, "label120");
  GLADE_HOOKUP_OBJECT (GestionEmp, label121, "label121");
  GLADE_HOOKUP_OBJECT (GestionEmp, ajTSMEmp, "ajTSMEmp");
  GLADE_HOOKUP_OBJECT (GestionEmp, ajModifEmploy, "ajModifEmploy");
  GLADE_HOOKUP_OBJECT (GestionEmp, ajErrTSMEMP, "ajErrTSMEMP");
  GLADE_HOOKUP_OBJECT (GestionEmp, mmmm, "mmmm");
  GLADE_HOOKUP_OBJECT (GestionEmp, ajSuppEmploy, "ajSuppEmploy");

  return GestionEmp;
}

