/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_auth (void);
GtkWidget* create_ajEspaceAd (void);
GtkWidget* create_Gestion_compteAdmin (void);
GtkWidget* create_Ajout_Employe (void);
GtkWidget* create_Modifier_Employe (void);
GtkWidget* create_Modifier_Client (void);
GtkWidget* create_GestionClients (void);
GtkWidget* create_Recherche (void);
GtkWidget* create_Espace_Emp (void);
GtkWidget* create_Ajout_client (void);
GtkWidget* create_Ajout_Admin (void);
GtkWidget* create_EspaceCli (void);
GtkWidget* create_GestionEmp (void);
