/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *auth;
  GtkWidget *ajEspaceAd;
  GtkWidget *Gestion_compteAdmin;
  GtkWidget *Ajout_Employe;
  GtkWidget *Modifier_Employe;
  GtkWidget *Modifier_Client;
  GtkWidget *GestionClients;
  GtkWidget *Recherche;
  GtkWidget *Espace_Emp;
  GtkWidget *Ajout_client;
  GtkWidget *Ajout_Admin;
  GtkWidget *EspaceCli;
  GtkWidget *GestionEmp;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  auth = create_auth ();
  gtk_widget_show (auth);
  /*ajEspaceAd = create_ajEspaceAd ();
  gtk_widget_show (ajEspaceAd);
  Gestion_compteAdmin = create_Gestion_compteAdmin ();
  gtk_widget_show (Gestion_compteAdmin);
  Ajout_Employe = create_Ajout_Employe ();
  gtk_widget_show (Ajout_Employe);
  Modifier_Employe = create_Modifier_Employe ();
  gtk_widget_show (Modifier_Employe);
  Modifier_Client = create_Modifier_Client ();
  gtk_widget_show (Modifier_Client);
  GestionClients = create_GestionClients ();
  gtk_widget_show (GestionClients);
  Recherche = create_Recherche ();
  gtk_widget_show (Recherche);
  Espace_Emp = create_Espace_Emp ();
  gtk_widget_show (Espace_Emp);
  Ajout_client = create_Ajout_client ();
  gtk_widget_show (Ajout_client);
  Ajout_Admin = create_Ajout_Admin ();
  gtk_widget_show (Ajout_Admin);
  EspaceCli = create_EspaceCli ();
  gtk_widget_show (EspaceCli);
  GestionEmp = create_GestionEmp ();
  gtk_widget_show (GestionEmp);*/

  gtk_main ();
  return 0;
}

